In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_weekly_history, get_stock_name, get_stock_currency
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 265 else '10y'
    rows = []
    for symbol in symbols:
        history = get_weekly_history(symbol, period=period, cache_days=2, currency='USD')
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 if len(changes) else float('nan') # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'currency': get_stock_currency(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map(lambda x: '' if pd.isna(x) else f'{x:.2%}')
    df['sharpe'] = df['sharpe'].map(lambda x: '' if pd.isna(x) else f'{x:.2f}')
    
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs)
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [24]:
crunch_etfs(261, 52) # 1y over 5y

Fetched history for SPY (1255 days)
Fetched history for SPYG (1255 days)
Fetched history for SPYV (1255 days)
Fetched history for QQQ (1255 days)
Fetched history for TOPT (491 days)
Fetched history for QTOP (491 days)
Fetched history for QTOP.AS (426 days)
Fetched history for TQQQ (1255 days)
Fetched history for IGM (1255 days)
Fetched history for MGK (1255 days)
Fetched history for SPMO (1255 days)
Fetched history for IDMO (1255 days)
Fetched history for MAGS (879 days)
Fetched history for FNGS (1255 days)
Fetched history for EXI (1255 days)
Fetched history for UFO (1255 days)
Fetched history for ROKT (1255 days)
Fetched history for QTUM (1255 days)
Fetched history for WQTM.DE (275 days)
Fetched history for EURUSD=X (2602 days)
Fetched history for NUKZ (681 days)
Fetched history for SMH (1255 days)
Fetched history for USD (1255 days)
Fetched history for PPA (1255 days)
Fetched history for IVDF.DE (492 days)
Fetched history for DAPP (1255 days)
Fetched history for BITQ (1255 days)
Fetched history for FBT.MI (1269 days)
Fetched history for A1P0.DE (137 days)
Fetched history for AIFS.DE (462 days)
Fetched history for LVHI (1255 days)
Fetched history for EHF1.DE (1273 days)
Fetched history for ESIF.DE (1275 days)
Fetched history for EXV1.DE (1274 days)
Fetched history for VDIV.DE (1273 days)
Fetched history for JEDI.DE (1093 days)
Fetched history for XLKS.MI (1270 days)
Fetched history for XAIX.DE (1274 days)
Fetched history for SMH.MI (1269 days)
Fetched history for CHIP.PA (1281 days)
Fetched history for DFEN.DE (894 days)
Fetched history for ASWC.DE (830 days)
Fetched history for IWDA.AS (1280 days)
Fetched history for IS3S.DE (1273 days)
Fetched history for IWMO.MI (1269 days)
Fetched history for 5MVL.DE (1240 days)
Fetched history for WMSE.DE (474 days)
Fetched history for XWEM.DE (830 days)
Fetched history for XDWI.DE (1273 days)
Fetched history for 4GLD.DE (1273 days)
Fetched history for BTC-USD (1827 days)
Fetched history for GC=F (1258 days)
Saved to data/stocks-52w-over-261w.csv (51/51)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,99,28.99%,7.75%,3.22
1,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,96,74.02%,22.96%,3.05
2,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,87,32.19%,10.63%,2.65
3,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,103,29.23%,9.78%,2.58
4,TOPT,iShares Top 20 U.S. Stocks ETF,USD,103,21.67%,6.85%,2.58
5,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,102,55.17%,20.39%,2.51
6,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,171,24.91%,9.47%,2.21
7,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,171,41.34%,18.34%,2.04
8,MAGS,Roundhill Magnificent Seven ETF,USD,183,34.79%,16.82%,1.83
9,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,185,46.65%,24.62%,1.73
10,LVHI,Franklin International Low Volatility High Div...,USD,261,18.05%,8.63%,1.63
11,NUKZ,Range Nuclear Renaissance ETF,USD,142,47.97%,27.99%,1.57
12,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,57,22.17%,11.93%,1.52
13,PPA,Invesco Aerospace & Defense ETF,USD,261,23.99%,13.35%,1.50
14,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,261,19.07%,10.11%,1.49
15,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,261,37.31%,24.59%,1.35
16,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,261,26.46%,17.61%,1.28
17,GC=F,Gold Dec 26,USD,261,25.02%,20.00%,1.05
18,IDMO,Invesco S&P International Developed Momentum ETF,USD,261,18.65%,13.94%,1.05
19,EXI,iShares Global Industrials ETF,USD,261,16.32%,11.87%,1.04
20,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,261,14.38%,10.03%,1.04
21,4GLD.DE,Xetra-Gold,EUR,261,24.91%,20.30%,1.03
22,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,261,16.35%,12.31%,1.00
23,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,261,26.30%,22.80%,0.98
24,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,261,12.80%,9.01%,0.98
25,QTUM,Defiance Quantum ETF,USD,261,29.85%,26.96%,0.96
26,SPMO,Invesco S&P 500 Momentum ETF,USD,261,24.09%,21.00%,0.96
27,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,261,42.63%,41.85%,0.92
28,SMH,VanEck Semiconductor ETF,USD,261,39.71%,41.32%,0.86
29,SPY,State Street SPDR S&P 500 ETF Trust,USD,261,15.33%,13.14%,0.86
30,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,261,24.83%,25.04%,0.83
31,IGM,iShares Expanded Tech Sector ETF,USD,261,24.47%,24.61%,0.83
32,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,14.28%,12.43%,0.83
33,FNGS,MicroSectors FANG+ ETN,USD,261,28.15%,30.07%,0.80
34,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,261,28.28%,30.56%,0.79
35,QQQ,Invesco QQQ Trust,USD,261,19.21%,19.45%,0.78
36,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,225,48.40%,56.83%,0.78
37,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,261,18.09%,19.03%,0.74
38,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,261,18.44%,19.80%,0.73
39,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,261,17.01%,18.17%,0.72
40,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,261,36.73%,47.05%,0.70
41,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,261,15.82%,17.09%,0.69
42,USD,ProShares Ultra Semiconductors,USD,261,73.32%,103.53%,0.67
43,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,261,18.42%,26.32%,0.55
44,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,261,11.03%,15.86%,0.44
45,TQQQ,ProShares UltraPro QQQ,USD,261,30.43%,63.22%,0.42
46,UFO,Procure Space ETF,USD,261,19.12%,47.70%,0.32
47,BTC-USD,Bitcoin USD,USD,261,22.77%,72.31%,0.26
48,BITQ,Bitwise Crypto Industry Innovators ETF,USD,261,17.20%,64.71%,0.20
49,DAPP,VanEck Digital Transformation ETF,USD,261,15.84%,71.33%,0.17
50,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,28,,,

In [25]:
crunch_etfs(156, 52) # 1y over 3y

Saved to data/stocks-52w-over-156w.csv (51/51)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,99,28.99%,7.75%,3.22
1,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,96,74.02%,22.96%,3.05
2,QTUM,Defiance Quantum ETF,USD,156,51.05%,16.78%,2.80
3,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,37.79%,12.18%,2.77
4,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,87,32.19%,10.63%,2.65
5,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,25.93%,8.31%,2.64
6,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.16%,19.21%,2.61
7,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,103,29.23%,9.78%,2.58
8,TOPT,iShares Top 20 U.S. Stocks ETF,USD,103,21.67%,6.85%,2.58
9,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,102,55.17%,20.39%,2.51
10,LVHI,Franklin International Low Volatility High Div...,USD,156,23.11%,7.92%,2.41
11,GC=F,Gold Dec 26,USD,156,40.64%,15.47%,2.37
12,4GLD.DE,Xetra-Gold,EUR,156,40.75%,15.68%,2.34
13,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.29%,12.14%,2.33
14,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.31%,6.66%,2.30
15,IDMO,Invesco S&P International Developed Momentum ETF,USD,156,25.27%,9.36%,2.27
16,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.02%,9.32%,2.26
17,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,156,23.96%,9.39%,2.13
18,PPA,Invesco Aerospace & Defense ETF,USD,156,30.66%,12.57%,2.12
19,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.16%,7.39%,2.05
20,EXI,iShares Global Industrials ETF,USD,156,20.94%,8.33%,2.03
21,QQQ,Invesco QQQ Trust,USD,156,23.38%,9.57%,2.03
22,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.61%,7.75%,2.01
23,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,20.89%,8.55%,1.98
24,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,156,23.10%,9.70%,1.97
25,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.26%,9.36%,1.95
26,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,156,41.35%,19.50%,1.92
27,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,156,30.76%,14.00%,1.91
28,IGM,iShares Expanded Tech Sector ETF,USD,156,30.70%,13.98%,1.91
29,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.34%,46.01%,1.83
30,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.42%,14.12%,1.80
31,UFO,Procure Space ETF,USD,156,64.59%,34.29%,1.77
32,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,52.06%,27.51%,1.75
33,FNGS,MicroSectors FANG+ ETN,USD,156,29.09%,14.39%,1.74
34,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.31%,16.93%,1.61
35,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,156,47.60%,27.41%,1.59
36,NUKZ,Range Nuclear Renaissance ETF,USD,142,47.97%,27.99%,1.57
37,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,57,22.17%,11.93%,1.52
38,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.44%,22.93%,1.42
39,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.26%,38.83%,1.29
40,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.92%,19.30%,1.29
41,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.30%,7.68%,1.21
42,TQQQ,ProShares UltraPro QQQ,USD,156,46.62%,40.19%,1.06
43,SMH,VanEck Semiconductor ETF,USD,156,49.22%,43.47%,1.04
44,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,45.76%,40.92%,1.02
45,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,156,20.22%,16.14%,1.01
46,USD,ProShares Ultra Semiconductors,USD,156,81.45%,88.63%,0.87
47,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,48.29%,53.86%,0.82
48,DAPP,VanEck Digital Transformation ETF,USD,156,42.09%,48.07%,0.79
49,BTC-USD,Bitcoin USD,USD,156,19.36%,61.76%,0.25
50,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,28,,,

In [8]:
# Long picks
crunch(98, 52, ['SPMO','LVHI','SPYM','SPYG','QQQ','SMH','MAGS','FNGS','QTOP','TOPT','XLG','MGK','USD',
                'TDIV.AS','CHIP.PA','4GLD.DE','JEDI.DE',
                'IWMO.MI', # IS3R.DE
                'XDEM.DE','IS3Q.DE','AIFS.DE','QTOP.AS',
                'XWEM.DE','QDVA.DE','WMSE.DE','FTGM.DE','CBUH.DE',
                'IWDA.AS', # iShares Core MSCI World UCITS ETF USD (Acc)
                'VGVF.DE', # Vanguard FTSE Developed World UCITS ETF Acc
                'VWCE.DE','IUSQ.DE','SPYI.DE',
                'XAIX.DE','TSWE.DE','IBCZ.DE','LYY0.DE'
                ])

,symbol,name,currency,weeks,gmean,std,sharpe
0,LVHI,Franklin International Low Volatility High Div...,USD,98,31.09%,4.16%,6.51
1,TSWE.DE,VanEck World Equal Weight Screened UCITS ETF,EUR,98,25.36%,4.49%,4.76
2,TDIV.AS,VanEck Morningstar Developed Markets Dividend ...,EUR,98,31.97%,6.76%,4.14
3,IBCZ.DE,iShares STOXX World Equity Multifactor UCITS E...,EUR,98,25.07%,5.35%,3.94
4,VGVF.DE,Vanguard FTSE Developed World UCITS ETF USD Ac...,EUR,98,23.54%,5.02%,3.90
5,VWCE.DE,Vanguard FTSE All-World UCITS ETF USD Accumula...,EUR,98,23.57%,5.04%,3.88
6,IUSQ.DE,iShares MSCI All Country World UCITS ETF USD Acc,EUR,98,23.61%,5.09%,3.85
7,LYY0.DE,Amundi MSCI All Country World Swap UCITS ETF E...,EUR,98,23.31%,5.09%,3.79
8,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,98,19.01%,3.97%,3.78
9,SPYI.DE,State Street SPDR MSCI All Country World Inves...,EUR,98,24.20%,5.38%,3.75
10,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,98,21.78%,4.82%,3.69
11,FTGM.DE,First Trust US Momentum UCITS ETF Class A USD Acc,EUR,98,29.30%,7.44%,3.40
12,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,98,25.53%,6.71%,3.21
13,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,98,28.85%,8.18%,3.04
14,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,98,73.01%,22.94%,3.01
15,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,98,26.56%,7.61%,2.97
16,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,98,20.85%,5.75%,2.93
17,SPMO,Invesco S&P 500 Momentum ETF,USD,98,29.52%,9.26%,2.76
18,XDEM.DE,Xtrackers MSCI World Momentum UCITS ETF 1C,EUR,98,25.09%,7.66%,2.75
19,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,98,86.66%,30.09%,2.75
20,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,98,38.84%,12.85%,2.71
21,SMH,VanEck Semiconductor ETF,USD,98,90.00%,32.76%,2.63
22,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,98,23.81%,7.79%,2.55
23,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,89,31.37%,10.86%,2.52
24,QQQ,Invesco QQQ Trust,USD,98,26.61%,9.01%,2.51
25,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,98,29.21%,10.40%,2.42
26,TOPT,iShares Top 20 U.S. Stocks ETF,USD,98,21.07%,7.31%,2.34
27,QDVA.DE,iShares Edge MSCI USA Momentum Factor UCITS ET...,EUR,98,25.30%,9.97%,2.14
28,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,98,20.13%,7.77%,2.08
29,CBUH.DE,iShares MSCI World Momentum Factor Advanced UC...,EUR,98,29.30%,12.46%,2.03
30,XLG,Invesco S&P 500 Top 50 ETF,USD,98,19.11%,7.77%,1.94
31,FNGS,MicroSectors FANG+ ETN,USD,98,18.79%,8.29%,1.78
32,MAGS,Roundhill Magnificent Seven ETF,USD,98,22.65%,11.18%,1.67
33,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,98,102.58%,59.55%,1.66
34,4GLD.DE,Xetra-Gold,EUR,98,39.77%,23.83%,1.50
35,USD,ProShares Ultra Semiconductors,USD,98,125.28%,83.32%,1.46

In [2]:
# World picks
crunch(262, 52, [
                'IWDA.AS', # iShares Core MSCI World UCITS ETF USD (Acc)
                'VGVF.DE', # Vanguard FTSE Developed World UCITS ETF Acc
                'VWCE.DE', # Vanguard FTSE All-World UCITS ETF USD Accumulation
                'IUSQ.DE', # iShares MSCI All Country World UCITS ETF USD Acc
                'SPYI.DE', # State Street SPDR MSCI All Country World Investable Market UCITS ETF
                ])

Fetched history for IWDA.AS (1280 days)
Fetched history for EURUSD=X (2602 days)
Fetched history for VGVF.DE (1273 days)
Fetched history for VWCE.DE (1273 days)
Fetched history for IUSQ.DE (1273 days)
Fetched history for SPYI.DE (1275 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,VGVF.DE,Vanguard FTSE Developed World UCITS ETF USD Ac...,EUR,261,15.01%,12.12%,0.91
1,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,14.70%,11.91%,0.90
2,IUSQ.DE,iShares MSCI All Country World UCITS ETF USD Acc,EUR,261,14.47%,12.12%,0.86
3,VWCE.DE,Vanguard FTSE All-World UCITS ETF USD Accumula...,EUR,261,14.41%,12.06%,0.86
4,SPYI.DE,State Street SPDR MSCI All Country World Inves...,EUR,261,14.10%,11.99%,0.84

In [28]:
# Dividend
crunch(156, 52, ['VDIV.DE','LVHI','EHF1.DE','EFAS','ISPA.DE','EVSD.DE','WQDA.AS','EXSH.DE','VGWD.DE','SELD.DE','WTEE.DE'])

Fetched history for EFAS (1255 days)
Fetched history for ISPA.DE (1275 days)
Fetched history for EVSD.DE (276 days)
Fetched history for WQDA.AS (1281 days)
Fetched history for EXSH.DE (1274 days)
Fetched history for VGWD.DE (1273 days)
Fetched history for SELD.DE (669 days)
Fetched history for WTEE.DE (1273 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,57,40.70%,4.46%,8.23
1,SELD.DE,Amundi Stoxx Europe Select Dividend 30 UCITS E...,EUR,138,37.66%,11.65%,2.89
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,25.93%,8.31%,2.64
3,LVHI,Franklin International Low Volatility High Div...,USD,156,23.11%,7.92%,2.41
4,VGWD.DE,Vanguard FTSE All-World High Dividend Yield UC...,EUR,156,19.88%,7.43%,2.14
5,ISPA.DE,iShares STOXX Global Select Dividend 100 UCITS...,EUR,156,24.16%,9.74%,2.07
6,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.16%,7.39%,2.05
7,EFAS,Global X MSCI SuperDividend EAFE ETF,USD,156,27.82%,12.11%,1.97
8,EXSH.DE,iShares STOXX Europe Select Dividend 30 UCITS ...,EUR,156,32.58%,15.60%,1.83
9,WQDA.AS,iShares MSCI World Quality Dividend Advanced U...,USD,156,18.67%,8.48%,1.73
10,WTEE.DE,WisdomTree Europe High Dividend UCITS ETF,EUR,156,23.54%,13.92%,1.40

In [29]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE','TQQQ','XDEV.DE','CBUI.DE','5MVL.DE','QDVI.DE','EUNL.DE','URTH'])

Fetched history for SPYM (1255 days)
Fetched history for XDEV.DE (1274 days)
Fetched history for QDVI.DE (1273 days)
Fetched history for EUNL.DE (1273 days)
Fetched history for URTH (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,URTH,iShares MSCI World ETF,USD,156,19.33%,6.41%,2.39
1,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.29%,12.14%,2.33
2,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.29%,6.67%,2.29
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.02%,9.32%,2.26
4,QQQ,Invesco QQQ Trust,USD,156,23.38%,9.57%,2.03
5,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,19.70%,7.76%,2.02
6,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.61%,7.75%,2.01
7,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.77%,13.18%,1.58
8,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.44%,22.93%,1.42
9,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,29.16%,19.43%,1.29
10,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.92%,19.30%,1.29
11,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.30%,7.68%,1.21
12,TQQQ,ProShares UltraPro QQQ,USD,156,46.62%,40.19%,1.06
13,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,29.70%,26.72%,0.96

In [30]:
# Megacap
crunch(156, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM','WLDR','QTOP.AS'])

Fetched history for XLG (1255 days)
Fetched history for WLDR (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,87,32.19%,10.63%,2.65
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,103,29.23%,9.78%,2.58
2,TOPT,iShares Top 20 U.S. Stocks ETF,USD,103,21.67%,6.85%,2.58
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.29%,12.14%,2.33
4,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.02%,9.32%,2.26
5,QQQ,Invesco QQQ Trust,USD,156,23.38%,9.57%,2.03
6,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,19.70%,7.76%,2.02
7,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.61%,7.75%,2.01
8,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.26%,9.36%,1.95
9,IGM,iShares Expanded Tech Sector ETF,USD,156,30.70%,13.98%,1.91
10,XLG,Invesco S&P 500 Top 50 ETF,USD,156,20.96%,9.32%,1.82
11,WLDR,Simplify Affinity World Leaders Equity ETF,USD,156,30.47%,14.69%,1.80
12,FNGS,MicroSectors FANG+ ETN,USD,156,29.09%,14.39%,1.74
13,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.31%,16.93%,1.61

In [31]:
# Growth
crunch(156, 52, ['SPY','SPYG','SPMO','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','IGM','RPG','SCHG'])

Fetched history for RPG (1255 days)
Fetched history for SCHG (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,103,29.23%,9.78%,2.58
1,TOPT,iShares Top 20 U.S. Stocks ETF,USD,103,21.67%,6.85%,2.58
2,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.29%,12.14%,2.33
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.02%,9.32%,2.26
4,QQQ,Invesco QQQ Trust,USD,156,23.38%,9.57%,2.03
5,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.61%,7.75%,2.01
6,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.26%,9.36%,1.95
7,IGM,iShares Expanded Tech Sector ETF,USD,156,30.70%,13.98%,1.91
8,XLG,Invesco S&P 500 Top 50 ETF,USD,156,20.96%,9.32%,1.82
9,RPG,Invesco S&P 500 Pure Growth ETF,USD,156,23.33%,10.98%,1.76
10,FNGS,MicroSectors FANG+ ETN,USD,156,29.09%,14.39%,1.74
11,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,156,20.87%,10.14%,1.66
12,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.31%,16.93%,1.61

In [32]:
# Value
crunch(156, 52, ['SPYV','IS3S.DE','IS3Q.DE','5MVL.DE','XDEV.DE','CBUI.DE','QDVI.DE','PSWD.DE','XWEV.DE'])

Fetched history for IS3Q.DE (1273 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,PSWD.DE,Invesco RAFI All-World Fundamental Value UCITS...,EUR,156,21.95%,8.80%,2.04
1,XWEV.DE,Xtrackers MSCI World Value ESG UCITS ETF 1C,EUR,156,25.39%,13.02%,1.64
2,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.77%,13.18%,1.58
3,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.44%,22.93%,1.42
4,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,156,14.81%,7.91%,1.37
5,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,29.16%,19.43%,1.29
6,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.92%,19.30%,1.29
7,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.30%,7.68%,1.21
8,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,29.70%,26.72%,0.96

In [33]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE','HNSC.MI'])

Fetched history for NVDA (1255 days)
Fetched history for AVGO (1255 days)
Fetched history for SOXX (1255 days)
Fetched history for PSI (1255 days)
Fetched history for SEC0.DE (1273 days)
Fetched history for HNSC.MI (895 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,USD,156,68.18%,33.76%,1.90
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.26%,38.83%,1.29
2,SMH,VanEck Semiconductor ETF,USD,156,49.22%,43.47%,1.04
3,HNSC.MI,HSBC NASDAQ Global Semiconductor UCITS ETF USD,EUR,156,59.81%,57.56%,0.97
4,NVDA,NVIDIA Corporation,USD,156,54.75%,56.17%,0.90
5,USD,ProShares Ultra Semiconductors,USD,156,81.45%,88.63%,0.87
6,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,48.29%,53.86%,0.82
7,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,EUR,156,48.69%,63.23%,0.71
8,SOXX,iShares Semiconductor ETF,USD,156,41.34%,56.39%,0.66
9,PSI,Invesco Semiconductors ETF,USD,156,46.39%,66.15%,0.64

In [ ]:
# Space picks
# see also https://www.justetf.com/en/how-to/invest-in-space.html
crunch(20, 10, ['UFO','ROKT','JEDI.DE','ARXX.DE','ST4R.DE','WSPC.DE','ORBT.MI','LUNA.DE','ASPT.DE'])

Fetched history for ASPT.DE (1 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,20,-1.81%,7.75%,-0.75
1,LUNA.DE,Global X Space Tech UCITS ETF,EUR,13,-15.63%,16.82%,-1.17
2,WSPC.DE,WisdomTree Space Economy UCITS ETF USD Acc,EUR,20,-9.20%,10.09%,-1.31
3,ORBT.MI,First Trust Bloomberg Space Economy UCITS ETF ...,EUR,12,-10.43%,8.83%,-1.63
4,ST4R.DE,iShares Space Technologies UCITS ETF USD Acc,EUR,20,-8.62%,7.54%,-1.67
5,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,20,-12.88%,10.05%,-1.68
6,UFO,Procure Space ETF,USD,20,-9.57%,6.90%,-1.97
7,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,20,-7.63%,5.71%,-2.03
8,ASPT.DE,Amundi Global Space Technologies UCITS ETF,EUR,1,,,

In [ ]:
# Quantum picks
# see also https://www.justetf.com/en-lu/how-to/invest-in-quantum-computing.html
crunch(45, 26, ['QTUM','WQTM','QUTM.DE','WQTM.DE','QOMP.DE','ASPT.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTUM,Defiance Quantum ETF,USD,45,30.43%,12.46%,2.12
1,QOMP.DE,iShares Quantum Computing UCITS ETF USD (Acc),EUR,45,21.17%,12.56%,1.37
2,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,45,20.86%,13.93%,1.21
3,WQTM,WisdomTree Quantum Computing Fund,USD,45,20.72%,14.94%,1.12
4,QUTM.DE,VanEck Quantum Computing UCITS ETF A USD Acc,EUR,45,15.53%,11.32%,1.02

In [36]:
# Power picks
crunch(156, 52, ['NUKZ','NLR','AIPO','A1P0.DE','NUUR.AS','WNUC.DE','NUKL.DE','RCTR.MI','ASWA.DE',
                 'WDNR.DE','LOGS.DE','5MVW.DE','XDW0.DE','WNRG.MI','WENE.MI','STOR.AS','ESIE.DE','QDVF.DE'])

Fetched history for NLR (1255 days)
Fetched history for AIPO (305 days)
Fetched history for NUUR.AS (284 days)
Fetched history for WNUC.DE (401 days)
Fetched history for NUKL.DE (934 days)
Fetched history for RCTR.MI (170 days)
Fetched history for ASWA.DE (134 days)
Fetched history for WDNR.DE (1273 days)
Fetched history for LOGS.DE (624 days)
Fetched history for 5MVW.DE (1273 days)
Fetched history for XDW0.DE (1273 days)
Fetched history for WNRG.MI (1269 days)
Fetched history for WENE.MI (1140 days)
Fetched history for STOR.AS (426 days)
Fetched history for ESIE.DE (1259 days)
Fetched history for QDVF.DE (1273 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AIPO,Defiance AI & Power Infrastructure ETF,USD,64,37.62%,9.76%,3.44
1,STOR.AS,iShares Energy Storage & Hydrogen UCITS ETF US...,USD,87,102.59%,35.71%,2.76
2,NUUR.AS,iShares Nuclear Energy and Uranium Mining UCIT...,USD,58,11.51%,2.96%,2.54
3,LOGS.DE,Amundi STOXX Europe 600 Energy ESG Screened - Acc,EUR,129,49.74%,23.81%,1.92
4,NUKZ,Range Nuclear Renaissance ETF,USD,142,47.97%,27.99%,1.57
5,NUKL.DE,VanEck Uranium and Nuclear Technologies UCITS ...,EUR,156,44.90%,38.75%,1.06
6,NLR,VanEck Uranium and Nuclear ETF,USD,156,31.64%,31.06%,0.89
7,WNUC.DE,WisdomTree Uranium and Nuclear Energy UCITS ET...,EUR,83,55.86%,63.07%,0.82
8,5MVW.DE,iShares MSCI World Energy Sector UCITS ETF USD...,EUR,156,15.84%,19.12%,0.62
9,XDW0.DE,Xtrackers MSCI World Energy UCITS ETF 1C,EUR,156,15.77%,19.13%,0.62
10,WNRG.MI,State Street SPDR MSCI World Energy UCITS ETF,EUR,156,15.75%,19.11%,0.62
11,WENE.MI,iShares MSCI World Energy Sector Advanced UCIT...,EUR,156,14.70%,19.57%,0.55
12,ESIE.DE,iShares MSCI Europe Energy Sector UCITS ETF,EUR,156,17.55%,26.35%,0.51
13,QDVF.DE,iShares S&P 500 Energy Sector UCITS ETF USD (Acc),EUR,156,13.67%,19.75%,0.49
14,WDNR.DE,Amundi Global Bioenergy UCITS ETF EUR Acc,EUR,156,12.05%,28.81%,0.28
15,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,28,,,
16,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,35,,,
17,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,28,,,

In [37]:
# Defense picks
crunch(100, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE','ASWC.DE','ES6Y.DE','IVDF.DE','ARXX.DE','DFCU.DE'])

Fetched history for ITA (1255 days)
Fetched history for XAR (1255 days)
Fetched history for 4MMR.DE (522 days)
Fetched history for ES6Y.DE (1040 days)
Fetched history for DFCU.DE (75 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,100,55.11%,20.73%,2.47
1,ITA,iShares U.S. Aerospace & Defense ETF,USD,100,34.98%,17.44%,1.78
2,XAR,State Street SPDR S&P Aerospace & Defense ETF,USD,100,40.52%,21.04%,1.74
3,PPA,Invesco Aerospace & Defense ETF,USD,100,31.22%,15.92%,1.71
4,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,100,30.88%,18.60%,1.45
5,ES6Y.DE,L&G Cyber Security Innovation UCITS ETF USD Ac...,EUR,100,27.60%,23.39%,1.01
6,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,100,33.43%,32.26%,0.91
7,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,EUR,100,34.45%,36.25%,0.84
8,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,48,,,
9,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,15,,,

In [38]:
# Crypto picks
crunch(156, 52, ['DAPP','BITQ','BTC-USD','DAPP.MI'])

Fetched history for DAPP.MI (1269 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,45.76%,40.92%,1.02
1,DAPP,VanEck Digital Transformation ETF,USD,156,42.09%,48.07%,0.79
2,DAPP.MI,VanEck Crypto& Blockchain Innovators ETF A USD...,EUR,156,41.33%,48.20%,0.77
3,BTC-USD,Bitcoin USD,USD,156,19.36%,61.76%,0.25

In [39]:
# Financial picks
crunch(156, 52, ['EXV1.DE','ESIF.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,37.79%,12.18%,2.77
1,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.16%,19.21%,2.61

In [40]:
# Gold
crunch(156, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L'])

Fetched history for GLDM (1255 days)
Fetched history for IAUM (1255 days)
Fetched history for SGOL (1255 days)
Fetched history for BAR (1255 days)
Fetched history for AAAU (1255 days)
Fetched history for IAU (1255 days)
Fetched history for OUNZ (1255 days)
Fetched history for GLD (1255 days)
Fetched history for FGDL (1074 days)
Fetched history for GLDA.DE (1273 days)
Fetched history for PPFB.DE (1273 days)
Fetched history for 8PSG.DE (1274 days)
Fetched history for XGDU.DE (1274 days)
Fetched history for PHAU.L (1262 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,8PSG.DE,Invesco Physical Gold ETC,EUR,156,42.32%,15.54%,2.47
1,GC=F,Gold Dec 26,USD,156,40.64%,15.47%,2.37
2,FGDL,Franklin Responsibly Sourced Gold ETF,USD,156,40.51%,15.46%,2.36
3,4GLD.DE,Xetra-Gold,EUR,156,40.75%,15.68%,2.34
4,GLDM,SPDR Gold MiniShares,USD,156,40.55%,15.65%,2.34
5,PPFB.DE,iShares Physical Gold ETC,EUR,156,40.56%,15.66%,2.33
6,GLDA.DE,Amundi Physical Gold ETC C,EUR,156,40.56%,15.67%,2.33
7,IAUM,iShares Gold Trust Micro,USD,156,40.59%,15.68%,2.33
8,AAAU,Goldman Sachs Physical Gold ETF,USD,156,40.43%,15.66%,2.33
9,BAR,GraniteShares Gold Trust,USD,156,40.44%,15.67%,2.33
10,SGOL,abrdn Physical Gold Shares ETF,USD,156,40.44%,15.67%,2.32
11,IAU,iShares Gold Trust,USD,156,40.34%,15.66%,2.32
12,OUNZ,VanEck Merk Gold Trust,USD,156,40.33%,15.66%,2.32
13,PHAU.L,WisdomTree Physical Gold,USD,156,40.18%,15.63%,2.31
14,GLD,SPDR Gold Shares,USD,156,40.14%,15.65%,2.31
15,XGDU.DE,Xtrackers IE Physical Gold ETC,EUR,156,40.76%,15.97%,2.30

In [41]:
# Materials & Industrials
crunch(156, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

Fetched history for WIND.AS (1279 days)
Fetched history for WMIN.DE (1273 days)
Fetched history for PICK (1255 days)
Fetched history for XDWM.DE (1273 days)
Fetched history for COPX (1255 days)
Fetched history for URNM (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,EXI,iShares Global Industrials ETF,USD,156,20.94%,8.33%,2.03
1,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,20.89%,8.55%,1.98
2,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,EUR,156,20.83%,8.52%,1.97
3,WMIN.DE,VanEck S&P Global Mining UCITS ETF,EUR,156,39.10%,38.55%,0.91
4,COPX,Global X Copper Miners ETF,USD,156,41.70%,47.94%,0.79
5,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,EUR,156,13.93%,14.42%,0.69
6,PICK,iShares MSCI Global Metals & Mining Producers ETF,USD,156,22.21%,34.36%,0.53
7,URNM,Sprott Uranium Miners ETF,USD,156,13.20%,41.77%,0.22

In [42]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE',
                 'AIFS.DE','XAIX.DE','XMLD.DE','XDWT.DE','XLKS.MI','FTAI.MI'])

Fetched history for BAI (493 days)
Fetched history for WTAI (1213 days)
Fetched history for AGIX (560 days)
Fetched history for CHAT (852 days)
Fetched history for AIQ (1255 days)
Fetched history for BOTZ (1255 days)
Fetched history for ROBO (1255 days)
Fetched history for THNQ (1255 days)
Fetched history for ARKQ (1255 days)
Fetched history for LRNZ (1255 days)
Fetched history for WISE (711 days)
Fetched history for XMLD.DE (1273 days)
Fetched history for XDWT.DE (1273 days)
Fetched history for FTAI.MI (50 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,96,74.02%,22.96%,3.05
1,AGIX,KraneShares Artificial Intelligence and Techno...,USD,117,37.23%,12.89%,2.58
2,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.29%,12.14%,2.33
3,AIQ,Global X Artificial Intelligence & Technology ETF,USD,156,30.63%,12.65%,2.10
4,QQQ,Invesco QQQ Trust,USD,156,23.38%,9.57%,2.03
5,ARKQ,ARK Autonomous Technology & Robotics ETF,USD,156,49.77%,22.94%,2.00
6,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,156,30.76%,14.00%,1.91
7,IGM,iShares Expanded Tech Sector ETF,USD,156,30.70%,13.98%,1.91
8,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.42%,14.12%,1.80
9,FNGS,MicroSectors FANG+ ETN,USD,156,29.09%,14.39%,1.74
10,XDWT.DE,Xtrackers MSCI World Information Technology UC...,EUR,156,26.68%,13.02%,1.74
11,BAI,iShares A.I. Innovation and Tech Active ETF,USD,103,47.83%,25.58%,1.71
12,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.31%,16.93%,1.61
13,THNQ,Robo Global Artificial Intelligence ETF,USD,156,32.63%,18.25%,1.57
14,XMLD.DE,L&G Artificial Intelligence UCITS ETF,EUR,156,32.87%,18.41%,1.57
15,CHAT,Roundhill Generative AI & Technology ETF,USD,156,50.20%,33.33%,1.39
16,WTAI,WisdomTree Artificial Intelligence and Innovat...,USD,156,34.22%,28.42%,1.06
17,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",USD,156,18.29%,16.11%,0.89
18,ROBO,Robo Global Robotics and Automation Index ETF,USD,156,18.52%,18.06%,0.80
19,WISE,Themes Generative Artificial Intelligence ETF,USD,149,17.87%,19.60%,0.71
20,BOTZ,Global X Robotics & Artificial Intelligence ETF,USD,156,11.79%,12.24%,0.64
21,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,10,,,

In [43]:
# Biotech
crunch(156, 52, ['IBB','XBI','BBH','FBT.MI','BTEC.SW','NBTK.DE','GN0M.DE'])

Fetched history for IBB (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,156,20.22%,16.14%,1.01
1,BTEC.SW,iShares Nasdaq US Biotechnology UCITS ETF USD ...,USD,156,18.04%,21.04%,0.67
2,NBTK.DE,Invesco NASDAQ Biotech UCITS ETF,EUR,156,18.02%,21.25%,0.66
3,XBI,State Street SPDR S&P Biotech ETF,USD,156,22.55%,33.19%,0.56
4,IBB,iShares Biotechnology ETF,USD,156,15.01%,20.32%,0.54
5,BBH,VanEck Biotech ETF,USD,156,10.15%,16.80%,0.37
6,GN0M.DE,Global X Genomics & Biotechnology UCITS ETF US...,EUR,156,8.20%,34.02%,0.12

In [44]:
# All UCITS
crunch(97, 52, ['VDIV.DE', 'EHF1.DE', 'ISPA.DE', 'EVSD.DE', 'WQDA.AS', 'EXSH.DE', 'VGWD.DE', 'SELD.DE', 'WTEE.DE', 'IWMO.MI',
                 'XDEM.DE', 'IS3Q.DE', 'XWEM.DE', 'QDVA.DE', 'IUMD.L', 'WMSE.DE', 'FTGM.DE', 'IS3S.DE', 'XDEV.DE', 'CBUI.DE',
                 '5MVL.DE', 'QDVI.DE', 'EUNL.DE', 'QTOP.AS', 'PSWD.DE', 'XWEV.DE', 'SMH.MI', 'CHIP.PA', 'SEC0.DE', 'HNSC.MI',
                 'JEDI.DE', 'ARXX.DE', 'ST4R.DE', 'WSPC.DE', 'ORBT.MI', 'LUNA.DE', 'QUTM.DE', 'WQTM.DE', 'QOMP.DE', 'A1P0.DE',
                 'NUUR.AS', 'WNUC.DE', 'NUKL.DE', 'RCTR.MI', 'ASWA.DE', 'WDNR.DE', 'LOGS.DE', '5MVW.DE', 'XDW0.DE', 'WNRG.MI',
                 'WENE.MI', 'STOR.AS', 'ESIE.DE', 'QDVF.DE', '4MMR.DE', 'DFEN.DE', 'ASWC.DE', 'ES6Y.DE', 'IVDF.DE', 'DFCU.DE',
                 'DAPP.MI', 'EXV1.DE', 'ESIF.DE', '4GLD.DE', 'GLDA.DE', 'PPFB.DE', '8PSG.DE', 'XGDU.DE', 'PHAU.L', 'XDWI.DE',
                 'WIND.AS', 'WMIN.DE', 'XDWM.DE', 'AIFS.DE', 'XAIX.DE', 'XMLD.DE', 'XDWT.DE', 'XLKS.MI', 'FTAI.MI', 'FBT.MI',
                 'BTEC.SW', 'NBTK.DE', 'GN0M.DE', 'CBUH.DE'])

Fetched history for XDEM.DE (1274 days)
Fetched history for QDVA.DE (1273 days)
Fetched history for IUMD.L (1262 days)
Fetched history for FTGM.DE (551 days)
Fetched history for CBUH.DE (1230 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,57,40.70%,4.46%,8.23
1,XWEV.DE,Xtrackers MSCI World Value ESG UCITS ETF 1C,EUR,97,38.41%,5.15%,6.68
2,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,97,38.70%,5.33%,6.51
3,PSWD.DE,Invesco RAFI All-World Fundamental Value UCITS...,EUR,97,30.28%,4.49%,5.85
4,VGWD.DE,Vanguard FTSE All-World High Dividend Yield UC...,EUR,97,26.82%,4.09%,5.58
...,...,...,...,...,...,...,...
79,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,28,,,
80,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,35,,,
81,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,28,,,
82,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,15,,,
83,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,10,,,