In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_weekly_history, get_stock_name, get_stock_currency
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 265 else '10y'
    rows = []
    for symbol in symbols:
        history = get_weekly_history(symbol, period=period, cache_days=5, currency='USD')
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'currency': get_stock_currency(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map('{:.2%}'.format)
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs + ['BRK-B'])
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Fetched history for XLKS.MI (1269 days)
Fetched history for IWDA.AS (1279 days)
Saved to data/stocks-52w-over-261w.csv (27/26)

,symbol,name,currency,weeks,gmean,std,sharpe
0,MAGS,Roundhill Magnificent Seven ETF,USD,179,35.49%,16.63%,1.893438
1,NUKZ,Range Nuclear Renaissance ETF,USD,138,51.19%,25.64%,1.840571
2,PPA,Invesco Aerospace & Defense ETF,USD,261,23.75%,13.73%,1.438390
3,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,261,18.59%,10.48%,1.393015
4,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,261,25.40%,18.83%,1.136312
5,GC=F,Gold Dec 26,USD,261,24.56%,20.45%,1.005498
6,4GLD.DE,Xetra-Gold,EUR,261,24.57%,20.60%,0.998314
7,IDMO,Invesco S&P International Developed Momentum ETF,USD,261,17.75%,14.96%,0.919321
8,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,261,25.37%,23.54%,0.908004
9,EXI,iShares Global Industrials ETF,USD,261,15.51%,12.98%,0.886738
10,SPMO,Invesco S&P 500 Momentum ETF,USD,261,23.12%,21.75%,0.878941
11,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,261,15.59%,13.35%,0.867996
12,QTUM,Defiance Quantum ETF,USD,261,28.19%,28.10%,0.860657
13,SMH,VanEck Semiconductor ETF,USD,261,37.24%,42.10%,0.789680
14,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,221,48.83%,57.33%,0.781976
15,SPY,State Street SPDR S&P 500 ETF Trust,USD,261,14.62%,13.82%,0.768314
16,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,13.70%,13.06%,0.742329
17,IGM,iShares Expanded Tech Sector ETF,USD,261,22.88%,25.86%,0.730052
18,FNGS,MicroSectors FANG+ ETN,USD,261,26.73%,31.35%,0.725166
19,QQQ,Invesco QQQ Trust,USD,261,18.07%,20.42%,0.688899
20,BRK-B,Berkshire Hathaway Inc.,USD,261,13.03%,13.22%,0.683193
21,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,261,16.08%,18.97%,0.636754
22,USD,ProShares Ultra Semiconductors,USD,261,68.34%,105.91%,0.607521
23,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,261,14.80%,17.87%,0.604512
24,BTC-USD,Bitcoin USD,USD,261,21.39%,73.05%,0.238008
25,BITQ,Bitwise Crypto Industry Innovators ETF,USD,261,14.41%,66.24%,0.157177
26,DAPP,VanEck Digital Transformation ETF,USD,261,12.85%,72.80%,0.121534

In [3]:
crunch_etfs(156, 52) # 1y over 3y

Saved to data/stocks-52w-over-156w.csv (27/26)

,symbol,name,currency,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,38.39%,11.73%,2.931807
1,QTUM,Defiance Quantum ETF,USD,156,50.51%,17.18%,2.707226
2,GC=F,Gold Dec 26,USD,156,41.98%,14.15%,2.683931
3,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,26.09%,8.26%,2.673827
4,4GLD.DE,Xetra-Gold,EUR,156,42.08%,14.35%,2.654793
5,PPA,Invesco Aerospace & Defense ETF,USD,156,32.37%,11.49%,2.470436
6,IDMO,Invesco S&P International Developed Momentum ETF,USD,156,25.67%,9.29%,2.331414
7,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.75%,9.63%,2.259375
8,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.75%,6.98%,2.256705
9,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
10,EXI,iShares Global Industrials ETF,USD,156,21.71%,8.48%,2.088582
11,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.76%,8.69%,2.044531
12,QQQ,Invesco QQQ Trust,USD,156,23.78%,9.83%,2.012254
13,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.26%,8.27%,1.964863
14,IGM,iShares Expanded Tech Sector ETF,USD,156,31.23%,14.42%,1.889055
15,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,156,23.81%,10.51%,1.884714
16,NUKZ,Range Nuclear Renaissance ETF,USD,138,51.19%,25.64%,1.840571
17,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.08%,46.24%,1.818523
18,FNGS,MicroSectors FANG+ ETN,USD,156,30.37%,14.91%,1.767761
19,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.99%,14.72%,1.765426
20,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.88%,17.11%,1.687605
21,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,49.82%,41.01%,1.117318
22,SMH,VanEck Semiconductor ETF,USD,156,48.72%,43.14%,1.036540
23,DAPP,VanEck Digital Transformation ETF,USD,156,47.26%,48.34%,0.895044
24,USD,ProShares Ultra Semiconductors,USD,156,84.79%,91.48%,0.883156
25,BRK-B,Berkshire Hathaway Inc.,USD,156,11.86%,12.82%,0.613466
26,BTC-USD,Bitcoin USD,USD,156,24.89%,63.36%,0.329764

In [4]:
# High Sharpe
crunch(156, 52, ['VDIV.DE','LVHI','EHF1.DE','EFAS'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,26.09%,8.26%,2.673827
1,LVHI,Franklin International Low Volatility High Div...,USD,156,22.94%,7.89%,2.401484
2,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.66%,7.33%,2.137642
3,EFAS,Global X MSCI SuperDividend EAFE ETF,USD,156,27.88%,12.08%,1.977466

In [5]:
# Momentum
crunch(156, 52, ['SPMO','IWMO.MI','IMTM','EEMO','IDMO','CGGO','VUG','SCHG','EFG','JIG','XDEM.DE','IS3Q.DE','URTH','EUNL.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,URTH,iShares MSCI World ETF,USD,156,19.75%,6.75%,2.334425
1,IDMO,Invesco S&P International Developed Momentum ETF,USD,156,25.67%,9.29%,2.331414
2,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.74%,6.98%,2.253300
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
4,IMTM,iShares MSCI Intl Momentum Factor ETF,USD,156,22.00%,8.53%,2.108609
5,XDEM.DE,Xtrackers MSCI World Momentum UCITS ETF 1C,EUR,156,23.80%,10.49%,1.888324
6,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,156,23.81%,10.51%,1.884714
7,VUG,Vanguard Morningstar Growth ETF,USD,156,22.35%,9.98%,1.838790
8,JIG,JPMorgan International Growth ETF,USD,156,16.61%,7.57%,1.666685
9,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,156,21.88%,10.80%,1.655582
10,CGGO,Capital Group Global Growth Equity ETF,USD,156,18.35%,10.44%,1.373670
11,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,156,15.27%,8.53%,1.322145
12,EFG,iShares MSCI EAFE Growth ETF,USD,156,11.92%,7.27%,1.088199
13,EEMO,Invesco S&P Emerging Markets Momentum ETF,USD,156,14.20%,15.48%,0.658994

In [6]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE','TQQQ'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.75%,9.63%,2.259375
1,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
2,QQQ,Invesco QQQ Trust,USD,156,23.78%,9.83%,2.012254
3,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,20.35%,8.28%,1.973462
4,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.26%,8.27%,1.964863
5,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,27.83%,19.03%,1.252336
6,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.86%,8.34%,1.181821
7,TQQQ,ProShares UltraPro QQQ,USD,156,48.04%,41.24%,1.067908

In [7]:
# Megacap
crunch(156, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM','WLDR'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,TOPT,iShares Top 20 U.S. Stocks ETF,USD,99,22.10%,6.95%,2.605788
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,99,29.37%,10.15%,2.499882
2,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.75%,9.63%,2.259375
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
4,QQQ,Invesco QQQ Trust,USD,156,23.78%,9.83%,2.012254
5,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,20.35%,8.28%,1.973462
6,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.26%,8.27%,1.964863
7,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,23.13%,9.89%,1.935242
8,IGM,iShares Expanded Tech Sector ETF,USD,156,31.23%,14.42%,1.889055
9,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.95%,9.78%,1.835350
10,WLDR,Affinity World Leaders Equity ETF,USD,156,30.21%,14.56%,1.800183
11,FNGS,MicroSectors FANG+ ETN,USD,156,30.37%,14.91%,1.767761
12,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.88%,17.11%,1.687605

In [8]:
# Growth
crunch(156, 52, ['SPY','SPYG','SPMO','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','IGM','RPG','SCHG'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,TOPT,iShares Top 20 U.S. Stocks ETF,USD,99,22.10%,6.95%,2.605788
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,99,29.37%,10.15%,2.499882
2,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.75%,9.63%,2.259375
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
4,QQQ,Invesco QQQ Trust,USD,156,23.78%,9.83%,2.012254
5,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.26%,8.27%,1.964863
6,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,23.13%,9.89%,1.935242
7,IGM,iShares Expanded Tech Sector ETF,USD,156,31.23%,14.42%,1.889055
8,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.95%,9.78%,1.835350
9,RPG,Invesco S&P 500 Pure Growth ETF,USD,156,23.65%,11.10%,1.770337
10,FNGS,MicroSectors FANG+ ETN,USD,156,30.37%,14.91%,1.767761
11,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.88%,17.11%,1.687605
12,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,156,21.88%,10.80%,1.655582

In [9]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,USD,156,72.61%,31.94%,2.147893
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.41%,38.92%,1.295033
2,SMH,VanEck Semiconductor ETF,USD,156,48.72%,43.14%,1.036540
3,NVDA,NVIDIA Corporation,USD,156,59.63%,60.24%,0.923475
4,USD,ProShares Ultra Semiconductors,USD,156,84.79%,91.48%,0.883156
5,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,46.73%,52.92%,0.807436
6,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,EUR,156,46.42%,62.16%,0.682412
7,SOXX,iShares Semiconductor ETF,USD,156,39.46%,55.19%,0.642488
8,PSI,Invesco Semiconductors ETF,USD,156,43.83%,65.29%,0.609953

In [10]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.08%,46.24%,1.818523
1,UFO,Procure Space ETF,USD,156,64.60%,34.26%,1.768727
2,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,51.67%,27.75%,1.717699

In [11]:
# Quantum picks
crunch(156, 26, ['QTUM','WQTM'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTUM,Defiance Quantum ETF,USD,156,22.53%,13.41%,1.381154
1,WQTM,WisdomTree Quantum Computing Fund,USD,49,24.21%,15.55%,1.300018

In [12]:
# Power picks
crunch(60, 52, ['NUKZ','NLR','AIPO'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,AIPO,Defiance AI & Power Infrastructure ETF,USD,60,43.86%,4.86%,8.198672
1,NUKZ,Range Nuclear Renaissance ETF,USD,60,11.55%,3.66%,2.063053
2,NLR,VanEck Uranium and Nuclear ETF,USD,60,0.28%,5.20%,-0.714820

In [13]:
# Defense picks
crunch(88, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,XAR,State Street SPDR S&P Aerospace & Defense ETF,USD,88,46.05%,18.90%,2.225014
1,ITA,iShares U.S. Aerospace & Defense ETF,USD,88,37.94%,15.86%,2.140407
2,PPA,Invesco Aerospace & Defense ETF,USD,88,34.88%,14.92%,2.069442
3,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,88,33.22%,31.65%,0.923062
4,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,EUR,88,33.74%,35.47%,0.838413

In [14]:
# Crypto picks
crunch(156, 52, ['DAPP','BITQ','BTC-USD'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,49.82%,41.01%,1.117318
1,DAPP,VanEck Digital Transformation ETF,USD,156,47.26%,48.34%,0.895044
2,BTC-USD,Bitcoin USD,USD,156,24.89%,63.36%,0.329764

In [15]:
# Financial picks
crunch(156, 52, ['EXV1.DE','ESIF.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,38.39%,11.73%,2.931807
1,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.45%,18.96%,2.661040

In [16]:
# Gold
crunch(156, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L',
                 'EURUSD=X'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,8PSG.DE,Invesco Physical Gold ETC,EUR,156,43.82%,14.02%,2.839948
1,GC=F,Gold Dec 26,USD,156,41.98%,14.15%,2.683931
2,FGDL,Franklin Responsibly Sourced Gold ETF,USD,156,41.83%,14.13%,2.676741
3,4GLD.DE,Xetra-Gold,EUR,156,42.08%,14.35%,2.654793
4,PPFB.DE,iShares Physical Gold ETC,EUR,156,41.89%,14.34%,2.642860
5,GLDA.DE,Amundi Physical Gold ETC C,EUR,156,41.89%,14.34%,2.642077
6,GLDM,SPDR Gold MiniShares,USD,156,41.84%,14.39%,2.630455
7,IAUM,iShares Gold Trust Micro,USD,156,41.87%,14.42%,2.626784
8,PHAU.L,WisdomTree Physical Gold,USD,156,41.50%,14.30%,2.621849
9,AAAU,Goldman Sachs Physical Gold ETF,USD,156,41.71%,14.39%,2.620137
10,BAR,GraniteShares Gold Trust,USD,156,41.73%,14.40%,2.619770
11,SGOL,abrdn Physical Gold Shares ETF,USD,156,41.73%,14.41%,2.618713
12,IAU,iShares Gold Trust,USD,156,41.63%,14.39%,2.614310
13,OUNZ,VanEck Merk Gold Trust,USD,156,41.62%,14.39%,2.613789
14,GLD,SPDR Gold Shares,USD,156,41.42%,14.38%,2.601494
15,XGDU.DE,Xtrackers IE Physical Gold ETC,EUR,156,42.10%,14.65%,2.599795
16,EURUSD=X,EUR/USD,USD,156,3.59%,5.47%,-0.074221

In [17]:
# Materials & Industrials
crunch(156, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,EXI,iShares Global Industrials ETF,USD,156,21.71%,8.48%,2.088582
1,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,EUR,156,21.71%,8.65%,2.046513
2,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.76%,8.69%,2.044531
3,WMIN.DE,VanEck S&P Global Mining UCITS ETF,EUR,156,38.65%,38.72%,0.894991
4,COPX,Global X Copper Miners ETF,USD,156,40.91%,48.03%,0.768499
5,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,EUR,156,14.05%,14.48%,0.693942
6,PICK,iShares MSCI Global Metals & Mining Producers ETF,USD,156,21.05%,34.35%,0.496490
7,URNM,Sprott Uranium Miners ETF,USD,156,14.28%,41.22%,0.249455

In [18]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,AGIX,KraneShares Artificial Intelligence and Techno...,USD,113,37.64%,13.16%,2.555127
1,SPMO,Invesco S&P 500 Momentum ETF,USD,156,33.45%,13.12%,2.244496
2,AIQ,Global X Artificial Intelligence & Technology ETF,USD,156,30.77%,12.71%,2.107212
3,ARKQ,ARK Autonomous Technology & Robotics ETF,USD,156,50.09%,22.52%,2.046582
4,QQQ,Invesco QQQ Trust,USD,156,23.78%,9.83%,2.012254
5,IGM,iShares Expanded Tech Sector ETF,USD,156,31.23%,14.42%,1.889055
6,FNGS,MicroSectors FANG+ ETN,USD,156,30.37%,14.91%,1.767761
7,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.88%,17.11%,1.687605
8,BAI,iShares A.I. Innovation and Tech Active ETF,USD,99,48.48%,26.47%,1.680408
9,THNQ,Robo Global Artificial Intelligence ETF,USD,156,32.15%,17.96%,1.567308
10,CHAT,Roundhill Generative AI & Technology ETF,USD,156,49.60%,33.44%,1.363460
11,WTAI,WisdomTree Artificial Intelligence and Innovat...,USD,156,32.75%,28.48%,1.009558
12,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",USD,156,17.70%,15.22%,0.900365
13,WISE,Themes Generative Artificial Intelligence ETF,USD,145,19.70%,18.40%,0.853239
14,ROBO,Robo Global Robotics and Automation Index ETF,USD,156,18.18%,18.08%,0.784018
15,BOTZ,Global X Robotics & Artificial Intelligence ETF,USD,156,12.89%,12.43%,0.715634

In [19]:
# Biotech
crunch(156, 52, ['IBB','XBI','BBH'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,XBI,State Street SPDR S&P Biotech ETF,USD,156,22.00%,32.76%,0.549608
1,IBB,iShares Biotechnology ETF,USD,156,14.26%,19.68%,0.521124
2,BBH,VanEck Biotech ETF,USD,156,9.23%,15.59%,0.335616