In [1]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_weekly_history, get_stock_name, get_stock_currency
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 265 else '10y'
    rows = []
    for symbol in symbols:
        history = get_weekly_history(symbol, period=period, cache_days=5, currency='USD')
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 if len(changes) else float('nan') # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'currency': get_stock_currency(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map(lambda x: '' if pd.isna(x) else f'{x:.2%}')
    df['sharpe'] = df['sharpe'].map(lambda x: '' if pd.isna(x) else f'{x:.2f}')
    
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs)
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Fetched history for SPYV (1255 days)
Fetched history for TOPT (486 days)
Fetched history for QTOP (486 days)
Fetched history for TQQQ (1255 days)
Fetched history for MGK (1255 days)
Fetched history for IDMO (1255 days)
Fetched history for WQTM.DE (270 days)
Fetched history for FBT.MI (1269 days)
Fetched history for EHF1.DE (1273 days)
Fetched history for EXV1.DE (1274 days)
Fetched history for VDIV.DE (1273 days)
Fetched history for XLKS.MI (1270 days)
Fetched history for SMH.MI (1269 days)
Fetched history for XDWI.DE (1273 days)
Fetched history for BTC-USD (1826 days)
Fetched history for GC=F (1258 days)
Saved to data/stocks-52w-over-261w.csv (51/51)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,98,29.22%,7.67%,3.29
1,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,95,73.98%,23.23%,3.01
2,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,101,56.30%,19.38%,2.70
3,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,86,32.28%,10.77%,2.63
4,TOPT,iShares Top 20 U.S. Stocks ETF,USD,102,21.72%,6.91%,2.56
5,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,102,29.21%,9.88%,2.55
6,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,170,24.93%,9.51%,2.20
7,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,170,41.69%,18.09%,2.08
8,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,56,25.31%,11.30%,1.89
9,MAGS,Roundhill Magnificent Seven ETF,USD,182,34.92%,16.82%,1.84
10,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,184,47.21%,24.13%,1.79
11,NUKZ,Range Nuclear Renaissance ETF,USD,141,48.77%,27.42%,1.63
12,LVHI,Franklin International Low Volatility High Div...,USD,261,17.90%,8.72%,1.59
13,PPA,Invesco Aerospace & Defense ETF,USD,261,23.93%,13.44%,1.48
14,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,261,18.95%,10.23%,1.46
15,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,261,36.93%,25.01%,1.32
16,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,261,26.18%,17.98%,1.23
17,GC=F,Gold Dec 26,USD,261,25.01%,20.01%,1.05
18,4GLD.DE,Xetra-Gold,EUR,261,24.87%,20.33%,1.03
19,IDMO,Invesco S&P International Developed Momentum ETF,USD,261,18.44%,14.18%,1.02
20,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,261,14.23%,10.25%,1.00
21,EXI,iShares Global Industrials ETF,USD,261,16.12%,12.15%,1.00
22,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,261,16.16%,12.57%,0.97
23,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,261,25.98%,23.06%,0.95
24,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,261,12.66%,9.14%,0.95
25,SPMO,Invesco S&P 500 Momentum ETF,USD,261,23.85%,21.17%,0.94
26,QTUM,Defiance Quantum ETF,USD,261,29.44%,27.25%,0.93
27,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,261,41.92%,42.23%,0.90
28,SMH,VanEck Semiconductor ETF,USD,261,39.10%,41.52%,0.85
29,SPY,State Street SPDR S&P 500 ETF Trust,USD,261,15.13%,13.33%,0.84
30,IGM,iShares Expanded Tech Sector ETF,USD,261,24.06%,24.93%,0.80
31,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,261,24.38%,25.36%,0.80
32,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,14.08%,12.65%,0.80
33,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,224,48.63%,56.90%,0.78
34,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,261,28.01%,30.72%,0.78
35,FNGS,MicroSectors FANG+ ETN,USD,261,27.75%,30.43%,0.78
36,QQQ,Invesco QQQ Trust,USD,261,18.91%,19.71%,0.76
37,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,261,17.75%,19.09%,0.72
38,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,261,18.17%,20.06%,0.71
39,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,261,16.76%,18.38%,0.69
40,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,261,36.05%,47.12%,0.68
41,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,261,15.56%,17.29%,0.67
42,USD,ProShares Ultra Semiconductors,USD,261,72.05%,104.14%,0.65
43,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,261,17.91%,26.50%,0.52
44,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,261,10.75%,15.86%,0.43
45,TQQQ,ProShares UltraPro QQQ,USD,261,29.36%,63.74%,0.40
46,UFO,Procure Space ETF,USD,261,18.80%,47.90%,0.31
47,BTC-USD,Bitcoin USD,USD,261,22.77%,72.31%,0.26
48,BITQ,Bitwise Crypto Industry Innovators ETF,USD,261,16.56%,65.06%,0.19
49,DAPP,VanEck Digital Transformation ETF,USD,261,15.15%,71.66%,0.16
50,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,27,,,

In [3]:
crunch_etfs(156, 52) # 1y over 3y

Saved to data/stocks-52w-over-156w.csv (51/51)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,98,29.22%,7.67%,3.29
1,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,95,73.98%,23.23%,3.01
2,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,37.98%,12.02%,2.83
3,QTUM,Defiance Quantum ETF,USD,156,50.94%,16.86%,2.78
4,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,101,56.30%,19.38%,2.70
5,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,25.98%,8.29%,2.65
6,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.27%,19.11%,2.63
7,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,86,32.28%,10.77%,2.63
8,TOPT,iShares Top 20 U.S. Stocks ETF,USD,102,21.72%,6.91%,2.56
9,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,102,29.21%,9.88%,2.55
10,4GLD.DE,Xetra-Gold,EUR,156,41.15%,15.21%,2.44
11,LVHI,Franklin International Low Volatility High Div...,USD,156,23.08%,7.92%,2.41
12,GC=F,Gold Dec 26,USD,156,40.63%,15.50%,2.36
13,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.58%,12.46%,2.29
14,IDMO,Invesco S&P International Developed Momentum ETF,USD,156,25.39%,9.35%,2.29
15,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.44%,6.77%,2.28
16,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.17%,9.42%,2.25
17,PPA,Invesco Aerospace & Defense ETF,USD,156,31.09%,12.29%,2.20
18,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,156,24.12%,9.52%,2.11
19,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.28%,7.36%,2.08
20,EXI,iShares Global Industrials ETF,USD,156,21.15%,8.40%,2.04
21,QQQ,Invesco QQQ Trust,USD,156,23.45%,9.63%,2.02
22,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.12%,8.58%,1.99
23,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.75%,7.91%,1.99
24,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,156,41.78%,19.14%,1.97
25,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,156,23.27%,9.92%,1.94
26,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.44%,9.52%,1.94
27,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,156,30.75%,13.99%,1.91
28,IGM,iShares Expanded Tech Sector ETF,USD,156,30.81%,14.10%,1.90
29,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,56,25.31%,11.30%,1.89
30,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.52%,45.84%,1.84
31,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.59%,14.31%,1.79
32,UFO,Procure Space ETF,USD,156,64.74%,34.13%,1.78
33,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,52.03%,27.54%,1.74
34,FNGS,MicroSectors FANG+ ETN,USD,156,29.38%,14.58%,1.74
35,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,156,48.35%,26.71%,1.66
36,NUKZ,Range Nuclear Renaissance ETF,USD,141,48.77%,27.42%,1.63
37,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.63%,17.00%,1.62
38,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.19%,22.86%,1.41
39,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.31%,38.87%,1.29
40,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.65%,19.23%,1.28
41,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.44%,7.88%,1.20
42,TQQQ,ProShares UltraPro QQQ,USD,156,46.87%,40.45%,1.06
43,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,47.10%,41.00%,1.05
44,SMH,VanEck Semiconductor ETF,USD,156,49.12%,43.41%,1.04
45,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,156,20.01%,16.03%,1.00
46,USD,ProShares Ultra Semiconductors,USD,156,82.41%,89.69%,0.87
47,DAPP,VanEck Digital Transformation ETF,USD,156,43.71%,48.29%,0.82
48,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,47.91%,53.64%,0.82
49,BTC-USD,Bitcoin USD,USD,156,19.38%,61.75%,0.25
50,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,27,,,

In [4]:
# Long term picks
crunch(262, 52, [#'SPMO','LVHI','SPY','SPYG','QQQ','SMH','MAGS','FNGS','QTOP',
                # 'TDIV.AS','CHIP.PA','4GLD.DE','JEDI.DE',
                # 'IWMO.MI', # IS3R.DE
                # 'XDEM.DE','IS3Q.DE','XDEV.DE','AIFS.DE','QTOP.AS',
                # 'XWEM.DE','QDVA.DE','QDVI.DE','WMSE.DE','FTGM.DE','CBUH.DE',
                'IWDA.AS', # iShares Core MSCI World UCITS ETF USD (Acc)
                'VWCE.DE','IUSQ.DE','SPYI.DE',
                # 'IS3S.DE', '5MVL.DE','XWEV.DE','CBUI.DE','PSWD.DE','XAIX.DE','TSWE.DE','IBCZ.DE','LYY0.DE'
                ])

,symbol,name,currency,weeks,gmean,std,sharpe
0,IWDA.AS,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,14.08%,12.65%,0.80
1,IUSQ.DE,iShares MSCI All Country World UCITS ETF USD Acc,EUR,262,13.85%,12.86%,0.77
2,VWCE.DE,Vanguard FTSE All-World UCITS ETF USD Accumula...,EUR,262,13.78%,12.80%,0.76
3,SPYI.DE,State Street SPDR MSCI All Country World Inves...,EUR,262,13.47%,12.73%,0.74

In [5]:
# Dividend
crunch(156, 52, ['VDIV.DE','LVHI','EHF1.DE','EFAS','ISPA.DE','EVSD.DE','WQDA.AS','EXSH.DE','VGWD.DE','SELD.DE','WTEE.DE'])

Fetched history for EFAS (1255 days)
Fetched history for ISPA.DE (1275 days)
Fetched history for EVSD.DE (271 days)
Fetched history for WQDA.AS (1281 days)
Fetched history for EXSH.DE (1274 days)
Fetched history for VGWD.DE (1273 days)
Fetched history for SELD.DE (664 days)
Fetched history for WTEE.DE (1273 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,56,41.26%,4.91%,7.59
1,SELD.DE,Amundi Stoxx Europe Select Dividend 30 UCITS E...,EUR,137,37.84%,11.61%,2.91
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,25.98%,8.29%,2.65
3,LVHI,Franklin International Low Volatility High Div...,USD,156,23.08%,7.92%,2.41
4,VGWD.DE,Vanguard FTSE All-World High Dividend Yield UC...,EUR,156,19.93%,7.45%,2.14
5,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.28%,7.36%,2.08
6,ISPA.DE,iShares STOXX Global Select Dividend 100 UCITS...,EUR,156,24.19%,9.73%,2.07
7,EFAS,Global X MSCI SuperDividend EAFE ETF,USD,156,27.83%,12.10%,1.97
8,EXSH.DE,iShares STOXX Europe Select Dividend 30 UCITS ...,EUR,156,32.54%,15.63%,1.83
9,WQDA.AS,iShares MSCI World Quality Dividend Advanced U...,USD,156,18.71%,8.52%,1.73
10,WTEE.DE,WisdomTree Europe High Dividend UCITS ETF,EUR,156,23.47%,13.95%,1.40

In [6]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE','TQQQ','XDEV.DE','CBUI.DE','5MVL.DE','QDVI.DE','EUNL.DE','URTH'])

Fetched history for SPYM (1255 days)
Fetched history for EUNL.DE (1273 days)
Fetched history for URTH (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,URTH,iShares MSCI World ETF,USD,156,19.45%,6.54%,2.36
1,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.58%,12.46%,2.29
2,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.43%,6.77%,2.28
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.17%,9.42%,2.25
4,QQQ,Invesco QQQ Trust,USD,156,23.45%,9.63%,2.02
5,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,19.85%,7.92%,2.00
6,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.75%,7.91%,1.99
7,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.68%,13.15%,1.57
8,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.19%,22.86%,1.41
9,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,28.88%,19.36%,1.29
10,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.65%,19.23%,1.28
11,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.44%,7.88%,1.20
12,TQQQ,ProShares UltraPro QQQ,USD,156,46.87%,40.45%,1.06
13,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,29.35%,26.54%,0.96

In [7]:
# Megacap
crunch(156, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM','WLDR','QTOP.AS'])

Fetched history for XLG (1255 days)
Fetched history for WLDR (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,86,32.28%,10.77%,2.63
1,TOPT,iShares Top 20 U.S. Stocks ETF,USD,102,21.72%,6.91%,2.56
2,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,102,29.21%,9.88%,2.55
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.58%,12.46%,2.29
4,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.17%,9.42%,2.25
5,QQQ,Invesco QQQ Trust,USD,156,23.45%,9.63%,2.02
6,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,19.85%,7.92%,2.00
7,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.75%,7.91%,1.99
8,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.44%,9.52%,1.94
9,IGM,iShares Expanded Tech Sector ETF,USD,156,30.81%,14.10%,1.90
10,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.18%,9.47%,1.81
11,WLDR,Simplify Affinity World Leaders Equity ETF,USD,156,30.42%,14.65%,1.80
12,FNGS,MicroSectors FANG+ ETN,USD,156,29.38%,14.58%,1.74
13,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.63%,17.00%,1.62

In [8]:
# Growth
crunch(156, 52, ['SPY','SPYG','SPMO','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','IGM','RPG','SCHG'])

Fetched history for RPG (1255 days)
Fetched history for SCHG (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,TOPT,iShares Top 20 U.S. Stocks ETF,USD,102,21.72%,6.91%,2.56
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,102,29.21%,9.88%,2.55
2,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.58%,12.46%,2.29
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.17%,9.42%,2.25
4,QQQ,Invesco QQQ Trust,USD,156,23.45%,9.63%,2.02
5,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,19.75%,7.91%,1.99
6,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.44%,9.52%,1.94
7,IGM,iShares Expanded Tech Sector ETF,USD,156,30.81%,14.10%,1.90
8,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.18%,9.47%,1.81
9,RPG,Invesco S&P 500 Pure Growth ETF,USD,156,23.39%,11.02%,1.76
10,FNGS,MicroSectors FANG+ ETN,USD,156,29.38%,14.58%,1.74
11,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,156,21.09%,10.34%,1.65
12,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.63%,17.00%,1.62

In [9]:
# Value
crunch(156, 52, ['SPYV','IS3S.DE','IS3Q.DE','5MVL.DE','XDEV.DE','CBUI.DE','QDVI.DE','PSWD.DE','XWEV.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,PSWD.DE,Invesco RAFI All-World Fundamental Value UCITS...,EUR,156,21.96%,8.80%,2.04
1,XWEV.DE,Xtrackers MSCI World Value ESG UCITS ETF 1C,EUR,156,25.31%,13.00%,1.64
2,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.68%,13.15%,1.57
3,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,36.19%,22.86%,1.41
4,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,156,14.94%,8.08%,1.35
5,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,28.88%,19.36%,1.29
6,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.65%,19.23%,1.28
7,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.44%,7.88%,1.20
8,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,29.35%,26.54%,0.96

In [10]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE','HNSC.MI'])

Fetched history for SOXX (1255 days)
Fetched history for PSI (1255 days)
Fetched history for SEC0.DE (1273 days)
Fetched history for HNSC.MI (890 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,USD,156,69.19%,33.43%,1.95
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.31%,38.87%,1.29
2,SMH,VanEck Semiconductor ETF,USD,156,49.12%,43.41%,1.04
3,HNSC.MI,HSBC NASDAQ Global Semiconductor UCITS ETF USD,EUR,156,59.45%,57.40%,0.97
4,NVDA,NVIDIA Corporation,USD,156,56.04%,57.57%,0.90
5,USD,ProShares Ultra Semiconductors,USD,156,82.41%,89.69%,0.87
6,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,47.91%,53.64%,0.82
7,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,EUR,156,48.13%,62.99%,0.70
8,SOXX,iShares Semiconductor ETF,USD,156,40.90%,56.12%,0.66
9,PSI,Invesco Semiconductors ETF,USD,156,45.76%,65.91%,0.63

In [11]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE','ARXX.DE','ST4R.DE','WSPC.DE','ORBT.MI','LUNA.DE'])

Fetched history for ARXX.DE (226 days)
Fetched history for ST4R.DE (85 days)
Fetched history for WSPC.DE (90 days)
Fetched history for ORBT.MI (44 days)
Fetched history for LUNA.DE (48 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.52%,45.84%,1.84
1,UFO,Procure Space ETF,USD,156,64.74%,34.13%,1.78
2,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,52.03%,27.54%,1.74
3,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,47,,,
4,ST4R.DE,iShares Space Technologies UCITS ETF USD Acc,EUR,17,,,
5,WSPC.DE,WisdomTree Space Economy UCITS ETF USD Acc,EUR,18,,,
6,ORBT.MI,First Trust Bloomberg Space Economy UCITS ETF ...,EUR,9,,,
7,LUNA.DE,Global X Space Tech UCITS ETF,EUR,10,,,

In [12]:
# Quantum picks
crunch(40, 26, ['QTUM','WQTM','QUTM.DE','WQTM.DE','QOMP.DE'])

Fetched history for WQTM (247 days)
Fetched history for QUTM.DE (345 days)
Fetched history for QOMP.DE (201 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTUM,Defiance Quantum ETF,USD,40,32.23%,8.32%,3.39
1,WQTM,WisdomTree Quantum Computing Fund,USD,40,23.90%,8.49%,2.34
2,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,40,23.88%,8.75%,2.27
3,QOMP.DE,iShares Quantum Computing UCITS ETF USD (Acc),EUR,40,23.89%,11.78%,1.69
4,QUTM.DE,VanEck Quantum Computing UCITS ETF A USD Acc,EUR,40,17.64%,10.52%,1.30

In [13]:
# Power picks
crunch(156, 52, ['NUKZ','NLR','AIPO','A1P0.DE','NUUR.AS','WNUC.DE','NUKL.DE','RCTR.MI','ASWA.DE',
                 'WDNR.DE','LOGS.DE','5MVW.DE','XDW0.DE','WNRG.MI','WENE.MI','STOR.AS','ESIE.DE','QDVF.DE'])

Fetched history for NUUR.AS (279 days)
Fetched history for WNUC.DE (396 days)
Fetched history for RCTR.MI (166 days)
Fetched history for ASWA.DE (129 days)
Fetched history for WDNR.DE (1273 days)
Fetched history for LOGS.DE (619 days)
Fetched history for 5MVW.DE (1273 days)
Fetched history for XDW0.DE (1273 days)
Fetched history for WNRG.MI (1269 days)
Fetched history for WENE.MI (1135 days)
Fetched history for STOR.AS (421 days)
Fetched history for ESIE.DE (1259 days)
Fetched history for QDVF.DE (1273 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,NUUR.AS,iShares Nuclear Energy and Uranium Mining UCIT...,USD,57,12.47%,2.09%,4.06
1,AIPO,Defiance AI & Power Infrastructure ETF,USD,63,39.01%,9.01%,3.89
2,STOR.AS,iShares Energy Storage & Hydrogen UCITS ETF US...,USD,86,103.71%,35.64%,2.80
3,LOGS.DE,Amundi STOXX Europe 600 Energy ESG Screened - Acc,EUR,128,49.73%,23.97%,1.91
4,NUKZ,Range Nuclear Renaissance ETF,USD,141,48.77%,27.42%,1.63
5,NUKL.DE,VanEck Uranium and Nuclear Technologies UCITS ...,EUR,156,45.82%,38.04%,1.10
6,NLR,VanEck Uranium and Nuclear ETF,USD,156,32.41%,30.42%,0.93
7,WNUC.DE,WisdomTree Uranium and Nuclear Energy UCITS ET...,EUR,82,59.38%,62.00%,0.89
8,5MVW.DE,iShares MSCI World Energy Sector UCITS ETF USD...,EUR,156,15.46%,18.86%,0.61
9,XDW0.DE,Xtrackers MSCI World Energy UCITS ETF 1C,EUR,156,15.39%,18.87%,0.60
10,WNRG.MI,State Street SPDR MSCI World Energy UCITS ETF,EUR,156,15.38%,18.85%,0.60
11,WENE.MI,iShares MSCI World Energy Sector Advanced UCIT...,EUR,156,14.34%,19.30%,0.54
12,ESIE.DE,iShares MSCI Europe Energy Sector UCITS ETF,EUR,156,17.03%,26.17%,0.50
13,QDVF.DE,iShares S&P 500 Energy Sector UCITS ETF USD (Acc),EUR,156,13.26%,19.36%,0.48
14,WDNR.DE,Amundi Global Bioenergy UCITS ETF EUR Acc,EUR,156,11.59%,28.55%,0.27
15,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,27,,,
16,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,34,,,
17,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,27,,,

In [14]:
# Defense picks
crunch(100, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE','ASWC.DE','ES6Y.DE','IVDF.DE','ARXX.DE','DFCU.DE'])

Fetched history for ITA (1255 days)
Fetched history for XAR (1255 days)
Fetched history for 4MMR.DE (517 days)
Fetched history for ES6Y.DE (1035 days)
Fetched history for DFCU.DE (70 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,100,56.10%,19.55%,2.67
1,ITA,iShares U.S. Aerospace & Defense ETF,USD,100,35.82%,16.63%,1.91
2,XAR,State Street SPDR S&P Aerospace & Defense ETF,USD,100,41.63%,19.90%,1.89
3,PPA,Invesco Aerospace & Defense ETF,USD,100,31.79%,15.32%,1.81
4,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,100,31.81%,18.31%,1.52
5,ES6Y.DE,L&G Cyber Security Innovation UCITS ETF USD Ac...,EUR,100,26.58%,22.97%,0.98
6,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,100,34.94%,31.49%,0.98
7,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,EUR,100,36.24%,35.52%,0.91
8,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,47,,,
9,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,14,,,

In [15]:
# Crypto picks
crunch(156, 52, ['DAPP','BITQ','BTC-USD','DAPP.MI'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,47.10%,41.00%,1.05
1,DAPP,VanEck Digital Transformation ETF,USD,156,43.71%,48.29%,0.82
2,DAPP.MI,VanEck Crypto& Blockchain Innovators ETF A USD...,EUR,156,42.94%,48.18%,0.81
3,BTC-USD,Bitcoin USD,USD,156,19.38%,61.75%,0.25

In [16]:
# Financial picks
crunch(156, 52, ['EXV1.DE','ESIF.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,37.98%,12.02%,2.83
1,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.27%,19.11%,2.63

In [17]:
# Gold
crunch(156, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L'])

Fetched history for GLDM (1255 days)
Fetched history for IAUM (1255 days)
Fetched history for SGOL (1255 days)
Fetched history for BAR (1255 days)
Fetched history for AAAU (1255 days)
Fetched history for IAU (1255 days)
Fetched history for OUNZ (1255 days)
Fetched history for GLD (1255 days)
Fetched history for FGDL (1069 days)
Fetched history for GLDA.DE (1273 days)
Fetched history for PPFB.DE (1273 days)
Fetched history for 8PSG.DE (1274 days)
Fetched history for XGDU.DE (1274 days)
Fetched history for PHAU.L (1262 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,8PSG.DE,Invesco Physical Gold ETC,EUR,156,42.79%,15.02%,2.58
1,FGDL,Franklin Responsibly Sourced Gold ETF,USD,156,40.89%,15.01%,2.46
2,4GLD.DE,Xetra-Gold,EUR,156,41.15%,15.21%,2.44
3,PPFB.DE,iShares Physical Gold ETC,EUR,156,40.96%,15.20%,2.43
4,GLDA.DE,Amundi Physical Gold ETC C,EUR,156,40.95%,15.20%,2.43
5,GLDM,SPDR Gold MiniShares,USD,156,40.93%,15.22%,2.43
6,IAUM,iShares Gold Trust Micro,USD,156,40.96%,15.26%,2.42
7,AAAU,Goldman Sachs Physical Gold ETF,USD,156,40.80%,15.23%,2.42
8,BAR,GraniteShares Gold Trust,USD,156,40.82%,15.24%,2.42
9,SGOL,abrdn Physical Gold Shares ETF,USD,156,40.81%,15.25%,2.41
10,PHAU.L,WisdomTree Physical Gold,USD,156,40.58%,15.16%,2.41
11,IAU,iShares Gold Trust,USD,156,40.71%,15.23%,2.41
12,OUNZ,VanEck Merk Gold Trust,USD,156,40.70%,15.23%,2.41
13,GLD,SPDR Gold Shares,USD,156,40.51%,15.22%,2.40
14,XGDU.DE,Xtrackers IE Physical Gold ETC,EUR,156,41.16%,15.51%,2.40
15,GC=F,Gold Dec 26,USD,156,40.63%,15.50%,2.36

In [18]:
# Materials & Industrials
crunch(156, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

Fetched history for WIND.AS (1279 days)
Fetched history for WMIN.DE (1273 days)
Fetched history for PICK (1255 days)
Fetched history for XDWM.DE (1273 days)
Fetched history for COPX (1255 days)
Fetched history for URNM (1255 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,EXI,iShares Global Industrials ETF,USD,156,21.15%,8.40%,2.04
1,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.12%,8.58%,1.99
2,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,EUR,156,21.07%,8.56%,1.99
3,WMIN.DE,VanEck S&P Global Mining UCITS ETF,EUR,156,39.06%,38.57%,0.91
4,COPX,Global X Copper Miners ETF,USD,156,41.61%,47.96%,0.78
5,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,EUR,156,13.96%,14.43%,0.69
6,PICK,iShares MSCI Global Metals & Mining Producers ETF,USD,156,21.96%,34.36%,0.52
7,URNM,Sprott Uranium Miners ETF,USD,156,13.62%,41.56%,0.23

In [19]:
# Tech & AI picks
crunch(156, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE',
                 'AIFS.DE','XAIX.DE','XMLD.DE','XDWT.DE','XLKS.MI','FTAI.MI'])

Fetched history for WTAI (1208 days)
Fetched history for AIQ (1255 days)
Fetched history for BOTZ (1255 days)
Fetched history for ROBO (1255 days)
Fetched history for THNQ (1255 days)
Fetched history for ARKQ (1255 days)
Fetched history for LRNZ (1255 days)
Fetched history for WISE (706 days)
Fetched history for XMLD.DE (1273 days)
Fetched history for XDWT.DE (1273 days)
Fetched history for FTAI.MI (44 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,95,73.98%,23.23%,3.01
1,AGIX,KraneShares Artificial Intelligence and Techno...,USD,116,37.31%,12.97%,2.57
2,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.58%,12.46%,2.29
3,AIQ,Global X Artificial Intelligence & Technology ETF,USD,156,30.66%,12.68%,2.10
4,ARKQ,ARK Autonomous Technology & Robotics ETF,USD,156,49.93%,22.73%,2.02
5,QQQ,Invesco QQQ Trust,USD,156,23.45%,9.63%,2.02
6,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,156,30.75%,13.99%,1.91
7,IGM,iShares Expanded Tech Sector ETF,USD,156,30.81%,14.10%,1.90
8,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.59%,14.31%,1.79
9,FNGS,MicroSectors FANG+ ETN,USD,156,29.38%,14.58%,1.74
10,XDWT.DE,Xtrackers MSCI World Information Technology UC...,EUR,156,26.79%,13.14%,1.73
11,BAI,iShares A.I. Innovation and Tech Active ETF,USD,102,47.92%,25.83%,1.70
12,MAGS,Roundhill Magnificent Seven ETF,USD,156,31.63%,17.00%,1.62
13,THNQ,Robo Global Artificial Intelligence ETF,USD,156,32.51%,18.15%,1.57
14,XMLD.DE,L&G Artificial Intelligence UCITS ETF,EUR,156,32.76%,18.34%,1.57
15,CHAT,Roundhill Generative AI & Technology ETF,USD,156,50.10%,33.34%,1.38
16,WTAI,WisdomTree Artificial Intelligence and Innovat...,USD,156,33.89%,28.42%,1.05
17,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",USD,156,18.21%,15.98%,0.89
18,ROBO,Robo Global Robotics and Automation Index ETF,USD,156,18.44%,18.05%,0.80
19,WISE,Themes Generative Artificial Intelligence ETF,USD,148,18.28%,19.36%,0.74
20,BOTZ,Global X Robotics & Artificial Intelligence ETF,USD,156,12.09%,12.33%,0.66
21,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,9,,,

In [20]:
# Biotech
crunch(156, 52, ['IBB','XBI','BBH','FBT.MI','BTEC.SW','NBTK.DE','GN0M.DE'])

Fetched history for IBB (1255 days)

KeyboardInterrupt:

In [ ]:
# All UCITS
crunch(97, 52, ['VDIV.DE', 'EHF1.DE', 'ISPA.DE', 'EVSD.DE', 'WQDA.AS', 'EXSH.DE', 'VGWD.DE', 'SELD.DE', 'WTEE.DE', 'IWMO.MI',
                 'XDEM.DE', 'IS3Q.DE', 'XWEM.DE', 'QDVA.DE', 'IUMD.L', 'WMSE.DE', 'FTGM.DE', 'IS3S.DE', 'XDEV.DE', 'CBUI.DE',
                 '5MVL.DE', 'QDVI.DE', 'EUNL.DE', 'QTOP.AS', 'PSWD.DE', 'XWEV.DE', 'SMH.MI', 'CHIP.PA', 'SEC0.DE', 'HNSC.MI',
                 'JEDI.DE', 'ARXX.DE', 'ST4R.DE', 'WSPC.DE', 'ORBT.MI', 'LUNA.DE', 'QUTM.DE', 'WQTM.DE', 'QOMP.DE', 'A1P0.DE',
                 'NUUR.AS', 'WNUC.DE', 'NUKL.DE', 'RCTR.MI', 'ASWA.DE', 'WDNR.DE', 'LOGS.DE', '5MVW.DE', 'XDW0.DE', 'WNRG.MI',
                 'WENE.MI', 'STOR.AS', 'ESIE.DE', 'QDVF.DE', '4MMR.DE', 'DFEN.DE', 'ASWC.DE', 'ES6Y.DE', 'IVDF.DE', 'DFCU.DE',
                 'DAPP.MI', 'EXV1.DE', 'ESIF.DE', '4GLD.DE', 'GLDA.DE', 'PPFB.DE', '8PSG.DE', 'XGDU.DE', 'PHAU.L', 'XDWI.DE',
                 'WIND.AS', 'WMIN.DE', 'XDWM.DE', 'AIFS.DE', 'XAIX.DE', 'XMLD.DE', 'XDWT.DE', 'XLKS.MI', 'FTAI.MI', 'FBT.MI',
                 'BTEC.SW', 'NBTK.DE', 'GN0M.DE', 'CBUH.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,55,45.10%,0.96%,42.73
1,XWEV.DE,Xtrackers MSCI World Value ESG UCITS ETF 1C,EUR,97,38.27%,5.38%,6.37
2,NUUR.AS,iShares Nuclear Energy and Uranium Mining UCIT...,USD,56,13.35%,1.67%,5.61
3,VGWD.DE,Vanguard FTSE All-World High Dividend Yield UC...,EUR,97,26.80%,4.19%,5.44
4,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,97,38.05%,6.34%,5.37
...,...,...,...,...,...,...,...
79,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,26,,,
80,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,33,,,
81,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,26,,,
82,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,13,,,
83,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,7,,,