In [2]:
import pandas as pd
from scipy.stats import gmean
from yfetch import get_weekly_history, get_stock_name, get_stock_currency
from symbols import my_etfs

risk_free_return = 0.04 # 4%

def crunch(history_weeks, weeks, symbols):
    assert history_weeks > weeks
    period = '5y' if history_weeks <= 265 else '10y'
    rows = []
    for symbol in symbols:
        history = get_weekly_history(symbol, period=period, cache_days=5, currency='USD')
        history = history.tail(history_weeks)
        changes = history.Close.pct_change(periods=weeks, fill_method=None).dropna()
        gmean_change = gmean(1 + changes) - 1 if len(changes) else float('nan') # geometric mean of changes
        std = changes.std()
        rows.append({
            'symbol': symbol,
            'name': get_stock_name(symbol),
            'currency': get_stock_currency(symbol),
            'weeks': len(history),
            'gmean': gmean_change,
            'std': std,
            'sharpe': (gmean_change - risk_free_return) / std,
        })
    
    df = pd.DataFrame(rows).sort_values(by='sharpe', ascending=False).reset_index(drop=True)
    for col in ['gmean', 'std']:
      df[col] = df[col].map(lambda x: '' if pd.isna(x) else f'{x:.2%}')
    df['sharpe'] = df['sharpe'].map(lambda x: '' if pd.isna(x) else f'{x:.2f}')
    
    # display(df)
    return df

def crunch_etfs(history_weeks, weeks=52):
    df = crunch(history_weeks, weeks, my_etfs)
    f = f'data/stocks-{weeks}w-over-{history_weeks}w.csv'
    df.to_csv(f, index=False)
    print(f'Saved to {f} ({len(df)}/{len(my_etfs)})')
    return df

In [2]:
crunch_etfs(261, 52) # 1y over 5y

Saved to data/stocks-52w-over-261w.csv (50/50)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,97,29.52%,7.51%,3.40
1,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,99,58.30%,17.69%,3.07
2,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,85,32.41%,10.91%,2.60
3,TOPT,iShares Top 20 U.S. Stocks ETF,USD,100,21.94%,6.96%,2.58
4,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,100,29.24%,10.09%,2.50
5,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,168,24.96%,9.59%,2.19
6,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,169,42.07%,17.80%,2.14
7,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,54,31.74%,13.22%,2.10
8,MAGS,Roundhill Magnificent Seven ETF,USD,180,35.27%,16.73%,1.87
9,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,183,47.82%,23.56%,1.86
10,NUKZ,Range Nuclear Renaissance ETF,USD,139,50.39%,26.24%,1.77
11,LVHI,Franklin International Low Volatility High Div...,USD,261,17.63%,8.88%,1.53
12,PPA,Invesco Aerospace & Defense ETF,USD,261,23.87%,13.55%,1.47
13,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,261,18.71%,10.43%,1.41
14,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,261,36.26%,25.68%,1.26
15,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,261,25.65%,18.60%,1.16
16,GC=F,Gold Dec 26,USD,261,24.79%,20.22%,1.03
17,4GLD.DE,Xetra-Gold,EUR,261,24.70%,20.50%,1.01
18,IDMO,Invesco S&P International Developed Momentum ETF,USD,261,18.21%,14.45%,0.98
19,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,261,13.93%,10.66%,0.93
20,EXI,iShares Global Industrials ETF,USD,261,15.70%,12.75%,0.92
21,SPMO,Invesco S&P 500 Momentum ETF,USD,261,23.59%,21.37%,0.92
22,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,261,25.37%,23.54%,0.91
23,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,261,15.78%,13.11%,0.90
24,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,261,12.41%,9.41%,0.89
25,QTUM,Defiance Quantum ETF,USD,261,28.57%,27.85%,0.88
26,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,261,40.45%,42.98%,0.85
27,SMH,VanEck Semiconductor ETF,USD,261,37.82%,41.91%,0.81
28,SPY,State Street SPDR S&P 500 ETF Trust,USD,261,14.76%,13.69%,0.79
29,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,222,48.80%,57.17%,0.78
30,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,261,27.40%,31.05%,0.75
31,IGM,iShares Expanded Tech Sector ETF,USD,261,23.23%,25.58%,0.75
32,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,261,23.49%,25.97%,0.75
33,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,261,13.69%,13.07%,0.74
34,FNGS,MicroSectors FANG+ ETN,USD,261,27.03%,31.07%,0.74
35,QQQ,Invesco QQQ Trust,USD,261,18.32%,20.21%,0.71
36,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,261,17.10%,19.21%,0.68
37,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,261,17.65%,20.56%,0.66
38,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,261,16.28%,18.80%,0.65
39,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,261,34.64%,47.18%,0.65
40,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,261,15.30%,17.49%,0.65
41,USD,ProShares Ultra Semiconductors,USD,261,69.47%,105.36%,0.62
42,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,261,16.87%,26.83%,0.48
43,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,261,10.11%,15.71%,0.39
44,TQQQ,ProShares UltraPro QQQ,USD,261,27.34%,64.77%,0.36
45,UFO,Procure Space ETF,USD,261,18.04%,48.33%,0.29
46,BTC-USD,Bitcoin USD,USD,261,21.70%,72.88%,0.24
47,BITQ,Bitwise Crypto Industry Innovators ETF,USD,261,15.13%,65.85%,0.17
48,DAPP,VanEck Digital Transformation ETF,USD,261,13.62%,72.42%,0.13
49,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,25,,,

In [3]:
crunch_etfs(156, 52) # 1y over 3y

Saved to data/stocks-52w-over-156w.csv (50/50)

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,97,29.52%,7.51%,3.40
1,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,99,58.30%,17.69%,3.07
2,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,38.33%,11.77%,2.92
3,QTUM,Defiance Quantum ETF,USD,156,50.65%,17.06%,2.73
4,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,26.12%,8.25%,2.68
5,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.45%,18.95%,2.66
6,GC=F,Gold Dec 26,USD,156,41.74%,14.37%,2.63
7,4GLD.DE,Xetra-Gold,EUR,156,41.89%,14.53%,2.61
8,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,85,32.41%,10.91%,2.60
9,TOPT,iShares Top 20 U.S. Stocks ETF,USD,100,21.94%,6.96%,2.58
10,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,100,29.24%,10.09%,2.50
11,LVHI,Franklin International Low Volatility High Div...,USD,156,23.03%,7.90%,2.41
12,PPA,Invesco Aerospace & Defense ETF,USD,156,31.60%,11.96%,2.31
13,IDMO,Invesco S&P International Developed Momentum ETF,USD,156,25.49%,9.32%,2.31
14,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.85%,12.72%,2.27
15,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.74%,6.99%,2.25
16,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.54%,9.59%,2.25
17,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.59%,7.33%,2.13
18,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,54,31.74%,13.22%,2.10
19,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,156,24.45%,9.80%,2.09
20,EXI,iShares Global Industrials ETF,USD,156,21.55%,8.49%,2.07
21,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,156,42.31%,18.76%,2.04
22,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.59%,8.69%,2.02
23,QQQ,Invesco QQQ Trust,USD,156,23.64%,9.77%,2.01
24,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.09%,8.18%,1.97
25,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.87%,9.78%,1.93
26,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,156,23.45%,10.15%,1.92
27,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,156,30.76%,13.99%,1.91
28,IGM,iShares Expanded Tech Sector ETF,USD,156,31.05%,14.31%,1.89
29,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.37%,45.96%,1.84
30,UFO,Procure Space ETF,USD,156,64.74%,34.12%,1.78
31,NUKZ,Range Nuclear Renaissance ETF,USD,139,50.39%,26.24%,1.77
32,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,156,29.98%,14.72%,1.77
33,FNGS,MicroSectors FANG+ ETN,USD,156,29.98%,14.81%,1.75
34,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,156,49.23%,25.93%,1.74
35,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,51.86%,27.64%,1.73
36,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.43%,17.13%,1.66
37,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,35.76%,22.67%,1.40
38,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.36%,38.90%,1.29
39,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.16%,19.10%,1.26
40,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.74%,8.23%,1.18
41,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,49.05%,41.09%,1.10
42,TQQQ,ProShares UltraPro QQQ,USD,156,47.56%,41.00%,1.06
43,SMH,VanEck Semiconductor ETF,USD,156,48.83%,43.20%,1.04
44,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,156,19.46%,15.53%,1.00
45,USD,ProShares Ultra Semiconductors,USD,156,83.94%,90.94%,0.88
46,DAPP,VanEck Digital Transformation ETF,USD,156,46.19%,48.42%,0.87
47,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,47.10%,53.10%,0.81
48,BTC-USD,Bitcoin USD,USD,156,23.41%,62.90%,0.31
49,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,25,,,

In [4]:
# Dividend
crunch(156, 52, ['VDIV.DE','LVHI','EHF1.DE','EFAS','ISPA.DE','EVSD.DE','WQDA.AS','EXSH.DE','VGWD.DE','SELD.DE','WTEE.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,55,45.10%,0.96%,42.73
1,SELD.DE,Amundi Stoxx Europe Select Dividend 30 UCITS E...,EUR,136,38.07%,11.53%,2.96
2,VDIV.DE,VanEck Morningstar Developed Markets Dividend ...,EUR,156,26.12%,8.25%,2.68
3,LVHI,Franklin International Low Volatility High Div...,USD,156,23.03%,7.90%,2.41
4,VGWD.DE,Vanguard FTSE All-World High Dividend Yield UC...,EUR,156,20.05%,7.49%,2.14
5,EHF1.DE,Amundi Index Solutions - Amundi MSCI Europe Hi...,EUR,156,19.59%,7.33%,2.13
6,ISPA.DE,iShares STOXX Global Select Dividend 100 UCITS...,EUR,156,24.29%,9.74%,2.08
7,EFAS,Global X MSCI SuperDividend EAFE ETF,USD,156,27.91%,12.07%,1.98
8,EXSH.DE,iShares STOXX Europe Select Dividend 30 UCITS ...,EUR,156,32.56%,15.63%,1.83
9,WQDA.AS,iShares MSCI World Quality Dividend Advanced U...,USD,156,18.79%,8.58%,1.72
10,WTEE.DE,WisdomTree Europe High Dividend UCITS ETF,EUR,156,23.49%,13.96%,1.40

In [5]:
# Momentum / Growth
crunch(97, 52, ['SPMO','IWMO.MI','IMTM','EEMO','IDMO','CGGO','VUG','SCHG','EFG','JIG','XDEM.DE','IS3Q.DE','XWEM.DE',
                 'QDVA.DE','IUMD.L','WMSE.DE','FTGM.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,97,29.52%,7.51%,3.40
1,JIG,JPMorgan International Growth ETF,USD,97,21.55%,5.41%,3.24
2,IMTM,iShares MSCI Intl Momentum Factor ETF,USD,97,27.00%,7.18%,3.21
3,XWEM.DE,Xtrackers MSCI World Momentum ESG UCITS ETF 1C,EUR,97,26.66%,7.12%,3.18
4,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,97,18.52%,4.71%,3.08
5,CGGO,Capital Group Global Growth Equity ETF,USD,97,25.31%,6.99%,3.05
6,IDMO,Invesco S&P International Developed Momentum ETF,USD,97,30.14%,8.58%,3.05
7,IWMO.MI,iShares Edge MSCI World Momentum Factor UCITS ...,EUR,97,25.16%,7.17%,2.95
8,XDEM.DE,Xtrackers MSCI World Momentum UCITS ETF 1C,EUR,97,25.14%,7.19%,2.94
9,SPMO,Invesco S&P 500 Momentum ETF,USD,97,29.70%,9.10%,2.82
10,FTGM.DE,First Trust US Momentum UCITS ETF Class A USD Acc,EUR,97,28.30%,9.04%,2.69
11,EFG,iShares MSCI EAFE Growth ETF,USD,97,16.14%,5.04%,2.41
12,VUG,Vanguard Morningstar Growth ETF,USD,97,19.26%,7.33%,2.08
13,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,97,17.90%,6.72%,2.07
14,QDVA.DE,iShares Edge MSCI USA Momentum Factor UCITS ET...,EUR,97,24.56%,10.54%,1.95
15,IUMD.L,iShares Edge MSCI USA Momentum Factor UCITS ET...,USD,97,24.43%,10.65%,1.92
16,EEMO,Invesco S&P Emerging Markets Momentum ETF,USD,97,26.10%,13.60%,1.63

In [6]:
# Broad market
crunch(156, 52, ['SPY','SPYM','SPYG','SPYV','SPMO','QQQ','IS3S.DE','TQQQ','XDEV.DE','CBUI.DE','5MVL.DE','QDVI.DE','EUNL.DE','URTH'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,URTH,iShares MSCI World ETF,USD,156,19.75%,6.75%,2.33
1,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.85%,12.72%,2.27
2,EUNL.DE,iShares Core MSCI World UCITS ETF USD (Acc),EUR,156,19.74%,6.99%,2.25
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.54%,9.59%,2.25
4,QQQ,Invesco QQQ Trust,USD,156,23.64%,9.77%,2.01
5,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,20.18%,8.19%,1.98
6,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.09%,8.18%,1.97
7,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.56%,13.10%,1.57
8,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,35.76%,22.67%,1.40
9,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,28.38%,19.22%,1.27
10,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.16%,19.10%,1.26
11,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.74%,8.23%,1.18
12,TQQQ,ProShares UltraPro QQQ,USD,156,47.56%,41.00%,1.06
13,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,28.70%,26.22%,0.94

In [12]:
# Megacap
crunch(156, 52, ['SPY','SPYM','SPYG','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','SPMO','IGM','WLDR','QTOP.AS'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTOP.AS,iShares VII PLC - iShares Nasdaq 100 Top 30 UC...,USD,85,32.41%,10.91%,2.60
1,TOPT,iShares Top 20 U.S. Stocks ETF,USD,100,21.94%,6.96%,2.58
2,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,100,29.24%,10.09%,2.50
3,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.85%,12.72%,2.27
4,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.54%,9.59%,2.25
5,QQQ,Invesco QQQ Trust,USD,156,23.64%,9.77%,2.01
6,SPYM,State Street SPDR Portfolio S&P 500 ETF,USD,156,20.18%,8.19%,1.98
7,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.09%,8.18%,1.97
8,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.87%,9.78%,1.93
9,IGM,iShares Expanded Tech Sector ETF,USD,156,31.05%,14.31%,1.89
10,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.68%,9.71%,1.82
11,WLDR,Affinity World Leaders Equity ETF,USD,156,30.31%,14.60%,1.80
12,FNGS,MicroSectors FANG+ ETN,USD,156,29.98%,14.81%,1.75
13,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.43%,17.13%,1.66

In [8]:
# Growth
crunch(156, 52, ['SPY','SPYG','SPMO','QQQ','MAGS','FNGS','XLG','MGK','TOPT','QTOP','IGM','RPG','SCHG'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,TOPT,iShares Top 20 U.S. Stocks ETF,USD,100,21.94%,6.96%,2.58
1,QTOP,iShares Nasdaq Top 30 Stocks ETF,USD,100,29.24%,10.09%,2.50
2,SPMO,Invesco S&P 500 Momentum ETF,USD,156,32.85%,12.72%,2.27
3,SPYG,State Street SPDR Portfolio S&P 500 Growth ETF,USD,156,25.54%,9.59%,2.25
4,QQQ,Invesco QQQ Trust,USD,156,23.64%,9.77%,2.01
5,SPY,State Street SPDR S&P 500 ETF Trust,USD,156,20.09%,8.18%,1.97
6,MGK,Vanguard Morningstar Mega Cap Growth ETF,USD,156,22.87%,9.78%,1.93
7,IGM,iShares Expanded Tech Sector ETF,USD,156,31.05%,14.31%,1.89
8,XLG,Invesco S&P 500 Top 50 ETF,USD,156,21.68%,9.71%,1.82
9,RPG,Invesco S&P 500 Pure Growth ETF,USD,156,23.55%,11.09%,1.76
10,FNGS,MicroSectors FANG+ ETN,USD,156,29.98%,14.81%,1.75
11,MAGS,Roundhill Magnificent Seven ETF,USD,156,32.43%,17.13%,1.66
12,SCHG,Schwab U.S. Large-Cap Growth ETF,USD,156,21.33%,10.48%,1.65

In [ ]:
# Value
crunch(156, 52, ['SPYV','IS3S.DE','IS3Q.DE','5MVL.DE','XDEV.DE','CBUI.DE','QDVI.DE','PSWD.DE','XWEV.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,PSWD.DE,Invesco RAFI All-World Fundamental Value UCITS...,EUR,156,22.04%,8.84%,2.04
1,XWEV.DE,Xtrackers MSCI World Value ESG UCITS ETF 1C,EUR,156,25.27%,13.00%,1.64
2,CBUI.DE,iShares MSCI World Value Factor Advaced UCITS ...,EUR,156,24.56%,13.10%,1.57
3,5MVL.DE,iShares Edge MSCI EM Value Factor UCITS ETF US...,EUR,156,35.76%,22.67%,1.40
4,IS3Q.DE,iShares Edge MSCI World Quality Factor UCITS E...,EUR,156,15.12%,8.31%,1.34
5,XDEV.DE,Xtrackers MSCI World Value UCITS ETF 1C,EUR,156,28.38%,19.22%,1.27
6,IS3S.DE,iShares Edge MSCI World Value Factor UCITS ETF...,EUR,156,28.16%,19.10%,1.26
7,SPYV,State Street SPDR Portfolio S&P 500 Value ETF,USD,156,13.74%,8.23%,1.18
8,QDVI.DE,iShares Edge MSCI USA Value Factor UCITS ETF U...,EUR,156,28.70%,26.22%,0.94

In [10]:
# Semiconductor
crunch(156, 52, ['SMH','USD','NVDA','AVGO','SOXX','PSI','SMH.MI','CHIP.PA','SEC0.DE','HNSC.MI'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,AVGO,Broadcom Inc.,USD,156,71.46%,32.51%,2.07
1,CHIP.PA,Amundi MSCI Semiconductors UCITS ETF Acc,EUR,156,54.36%,38.90%,1.29
2,SMH,VanEck Semiconductor ETF,USD,156,48.83%,43.20%,1.04
3,HNSC.MI,HSBC NASDAQ Global Semiconductor UCITS ETF USD,EUR,156,58.56%,56.93%,0.96
4,NVDA,NVIDIA Corporation,USD,156,58.42%,59.37%,0.92
5,USD,ProShares Ultra Semiconductors,USD,156,83.94%,90.94%,0.88
6,SMH.MI,VanEck Semiconductor UCITS ETF,EUR,156,47.10%,53.10%,0.81
7,SEC0.DE,iShares MSCI Global Semiconductors UCITS ETF U...,EUR,156,46.96%,62.35%,0.69
8,SOXX,iShares Semiconductor ETF,USD,156,39.90%,55.43%,0.65
9,PSI,Invesco Semiconductors ETF,USD,156,44.39%,65.38%,0.62

In [11]:
# Space picks
crunch(156, 52, ['UFO','ROKT','JEDI.DE','ARXX.DE','ST4R.DE','WSPC.DE','ORBT.MI','LUNA.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,JEDI.DE,VanEck Space Innovators UCITS ETF A USD Acc,EUR,156,88.37%,45.96%,1.84
1,UFO,Procure Space ETF,USD,156,64.74%,34.12%,1.78
2,ROKT,State Street SPDR S&P Kensho Final Frontiers ETF,USD,156,51.86%,27.64%,1.73
3,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,46,,,
4,ST4R.DE,iShares Space Technologies UCITS ETF USD Acc,EUR,16,,,
5,WSPC.DE,WisdomTree Space Economy UCITS ETF USD Acc,EUR,17,,,
6,ORBT.MI,First Trust Bloomberg Space Economy UCITS ETF ...,EUR,7,,,
7,LUNA.DE,Global X Space Tech UCITS ETF,EUR,9,,,

In [21]:
# Quantum picks
crunch(40, 26, ['QTUM','WQTM','QUTM.DE','WQTM.DE','QOMP.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,QTUM,Defiance Quantum ETF,USD,40,32.44%,8.94%,3.18
1,WQTM.DE,WisdomTree Quantum Computing UCITS ETF - USD Acc,EUR,40,24.16%,9.44%,2.14
2,WQTM,WisdomTree Quantum Computing Fund,USD,40,25.00%,10.08%,2.08
3,QOMP.DE,iShares Quantum Computing UCITS ETF USD (Acc),EUR,40,21.54%,9.74%,1.80
4,QUTM.DE,VanEck Quantum Computing UCITS ETF A USD Acc,EUR,40,15.91%,8.58%,1.39

In [5]:
# Power picks
crunch(156, 52, ['NUKZ','NLR','AIPO','A1P0.DE','NUUR.AS','WNUC.DE','NUKL.DE','RCTR.MI','ASWA.DE',
                 'WDNR.DE','LOGS.DE','5MVW.DE','XDW0.DE','WNRG.MI','WENE.MI','STOR.AS','ESIE.DE','QDVF.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,NUUR.AS,iShares Nuclear Energy and Uranium Mining UCIT...,USD,56,13.35%,1.67%,5.61
1,AIPO,Defiance AI & Power Infrastructure ETF,USD,61,41.83%,7.35%,5.15
2,STOR.AS,iShares Energy Storage & Hydrogen UCITS ETF US...,USD,85,105.10%,35.33%,2.86
3,LOGS.DE,Amundi STOXX Europe 600 Energy ESG Screened - Acc,EUR,127,49.80%,24.12%,1.90
4,NUKZ,Range Nuclear Renaissance ETF,USD,139,50.39%,26.24%,1.77
5,NUKL.DE,VanEck Uranium and Nuclear Technologies UCITS ...,EUR,156,46.69%,37.36%,1.14
6,NLR,VanEck Uranium and Nuclear ETF,USD,156,33.75%,29.30%,1.02
7,WNUC.DE,WisdomTree Uranium and Nuclear Energy UCITS ET...,EUR,81,63.19%,60.71%,0.97
8,5MVW.DE,iShares MSCI World Energy Sector UCITS ETF USD...,EUR,156,15.23%,18.72%,0.60
9,XDW0.DE,Xtrackers MSCI World Energy UCITS ETF 1C,EUR,156,15.16%,18.72%,0.60
10,WNRG.MI,State Street SPDR MSCI World Energy UCITS ETF,EUR,156,15.15%,18.71%,0.60
11,WENE.MI,iShares MSCI World Energy Sector Advanced UCIT...,EUR,156,14.14%,19.18%,0.53
12,ESIE.DE,iShares MSCI Europe Energy Sector UCITS ETF,EUR,156,16.54%,26.06%,0.48
13,QDVF.DE,iShares S&P 500 Energy Sector UCITS ETF USD (Acc),EUR,156,13.01%,19.15%,0.47
14,WDNR.DE,Amundi Global Bioenergy UCITS ETF EUR Acc,EUR,156,11.24%,28.44%,0.25
15,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,25,,,
16,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,33,,,
17,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,26,,,

In [4]:
# Defense picks
crunch(100, 52, ['ITA','PPA','XAR','4MMR.DE','DFEN.DE','ASWC.DE','ES6Y.DE','IVDF.DE','ARXX.DE','DFCU.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,100,57.43%,18.33%,2.91
1,ITA,iShares U.S. Aerospace & Defense ETF,USD,100,37.04%,15.74%,2.10
2,XAR,State Street SPDR S&P Aerospace & Defense ETF,USD,100,43.21%,18.79%,2.09
3,PPA,Invesco Aerospace & Defense ETF,USD,100,32.70%,14.57%,1.97
4,ASWC.DE,HANetf ICAV - Future of Defence UCITS ETF - Ac...,EUR,100,33.12%,18.44%,1.58
5,DFEN.DE,VanEck Defense ETF A USD Acc,EUR,100,36.91%,30.94%,1.06
6,4MMR.DE,Global X Defence Tech UCITS ETF USD Accumulating,EUR,100,38.54%,35.11%,0.98
7,ES6Y.DE,L&G Cyber Security Innovation UCITS ETF USD Ac...,EUR,100,25.27%,22.02%,0.97
8,ARXX.DE,ARK Space & Defence Innovation UCITS ETF A USD...,EUR,46,,,
9,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,13,,,

In [15]:
# Crypto picks
crunch(156, 52, ['DAPP','BITQ','BTC-USD','DAPP.MI'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,BITQ,Bitwise Crypto Industry Innovators ETF,USD,156,49.05%,41.09%,1.10
1,DAPP,VanEck Digital Transformation ETF,USD,156,46.19%,48.42%,0.87
2,DAPP.MI,VanEck Crypto& Blockchain Innovators ETF A USD...,EUR,156,45.43%,48.39%,0.86
3,BTC-USD,Bitcoin USD,USD,156,23.41%,62.90%,0.31

In [16]:
# Financial picks
crunch(156, 52, ['EXV1.DE','ESIF.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,ESIF.DE,iShares MSCI Europe Financials Sector UCITS ETF,EUR,156,38.33%,11.77%,2.92
1,EXV1.DE,iShares STOXX Europe 600 Banks UCITS ETF (DE),EUR,156,54.45%,18.95%,2.66

In [17]:
# Gold
crunch(156, 52, ['GC=F','GLDM','IAUM','SGOL','BAR','AAAU','IAU','OUNZ','GLD','FGDL',
                 '4GLD.DE','GLDA.DE','PPFB.DE','8PSG.DE','XGDU.DE','PHAU.L'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,8PSG.DE,Invesco Physical Gold ETC,EUR,156,43.57%,14.26%,2.78
1,FGDL,Franklin Responsibly Sourced Gold ETF,USD,156,41.64%,14.32%,2.63
2,GC=F,Gold Dec 26,USD,156,41.74%,14.37%,2.63
3,4GLD.DE,Xetra-Gold,EUR,156,41.89%,14.53%,2.61
4,PPFB.DE,iShares Physical Gold ETC,EUR,156,41.70%,14.52%,2.60
5,GLDA.DE,Amundi Physical Gold ETC C,EUR,156,41.70%,14.53%,2.60
6,GLDM,SPDR Gold MiniShares,USD,156,41.66%,14.56%,2.59
7,IAUM,iShares Gold Trust Micro,USD,156,41.69%,14.59%,2.58
8,PHAU.L,WisdomTree Physical Gold,USD,156,41.32%,14.48%,2.58
9,AAAU,Goldman Sachs Physical Gold ETF,USD,156,41.53%,14.57%,2.58
10,BAR,GraniteShares Gold Trust,USD,156,41.55%,14.58%,2.58
11,SGOL,abrdn Physical Gold Shares ETF,USD,156,41.54%,14.58%,2.57
12,IAU,iShares Gold Trust,USD,156,41.44%,14.57%,2.57
13,OUNZ,VanEck Merk Gold Trust,USD,156,41.43%,14.57%,2.57
14,GLD,SPDR Gold Shares,USD,156,41.24%,14.56%,2.56
15,XGDU.DE,Xtrackers IE Physical Gold ETC,EUR,156,41.90%,14.84%,2.55

In [18]:
# Materials & Industrials
crunch(156, 52, ['XDWI.DE','WIND.AS','EXI','WMIN.DE','PICK','XDWM.DE','COPX','URNM'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,EXI,iShares Global Industrials ETF,USD,156,21.55%,8.49%,2.07
1,WIND.AS,State Street SPDR MSCI World Industrials UCITS...,EUR,156,21.53%,8.66%,2.03
2,XDWI.DE,Xtrackers MSCI World Industrials UCITS ETF 1C,EUR,156,21.59%,8.69%,2.02
3,WMIN.DE,VanEck S&P Global Mining UCITS ETF,EUR,156,39.00%,38.59%,0.91
4,COPX,Global X Copper Miners ETF,USD,156,41.35%,47.98%,0.78
5,XDWM.DE,Xtrackers MSCI World Materials UCITS ETF 1C,EUR,156,14.09%,14.50%,0.70
6,PICK,iShares MSCI Global Metals & Mining Producers ETF,USD,156,21.49%,34.35%,0.51
7,URNM,Sprott Uranium Miners ETF,USD,156,14.18%,41.28%,0.25

In [7]:
# Tech & AI picks
crunch(94, 52, ['MAGS','FNGS','SPMO','IGM','QQQ','BAI','WTAI','AGIX','CHAT','AIQ','BOTZ','ROBO','THNQ','ARKQ','LRNZ','WISE',
                 'AIFS.DE','XAIX.DE','XMLD.DE','XDWT.DE','XLKS.MI','FTAI.MI'])

Fetched history for FTAI.MI (34 days)

,symbol,name,currency,weeks,gmean,std,sharpe
0,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,94,73.98%,23.51%,2.98
1,SPMO,Invesco S&P 500 Momentum ETF,USD,94,30.19%,9.21%,2.84
2,AIQ,Global X Artificial Intelligence & Technology ETF,USD,94,38.26%,12.42%,2.76
3,XAIX.DE,Xtrackers Artificial Intelligence & Big Data U...,EUR,94,38.85%,12.99%,2.68
4,XLKS.MI,Invesco Technology S&P US Select Sector UCITS ETF,EUR,94,34.04%,11.51%,2.61
5,XDWT.DE,Xtrackers MSCI World Information Technology UC...,EUR,94,32.44%,11.24%,2.53
6,QQQ,Invesco QQQ Trust,USD,94,26.98%,9.20%,2.50
7,IGM,iShares Expanded Tech Sector ETF,USD,94,36.09%,12.98%,2.47
8,CHAT,Roundhill Generative AI & Technology ETF,USD,94,77.68%,30.43%,2.42
9,XMLD.DE,L&G Artificial Intelligence UCITS ETF,EUR,94,44.91%,17.89%,2.29
10,ROBO,Robo Global Robotics and Automation Index ETF,USD,94,35.27%,13.91%,2.25
11,THNQ,Robo Global Artificial Intelligence ETF,USD,94,44.13%,18.17%,2.21
12,AGIX,KraneShares Artificial Intelligence and Techno...,USD,94,36.71%,14.98%,2.18
13,WTAI,WisdomTree Artificial Intelligence and Innovat...,USD,94,58.25%,24.87%,2.18
14,ARKQ,ARK Autonomous Technology & Robotics ETF,USD,94,51.79%,22.51%,2.12
15,MAGS,Roundhill Magnificent Seven ETF,USD,94,23.79%,11.11%,1.78
16,FNGS,MicroSectors FANG+ ETN,USD,94,19.13%,8.59%,1.76
17,BAI,iShares A.I. Innovation and Tech Active ETF,USD,94,50.10%,27.25%,1.69
18,LRNZ,"TrueShares Technology, AI and Deep Learning ETF",USD,94,25.24%,15.44%,1.38
19,BOTZ,Global X Robotics & Artificial Intelligence ETF,USD,94,16.55%,10.71%,1.17
20,WISE,Themes Generative Artificial Intelligence ETF,USD,94,8.63%,15.37%,0.30
21,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,7,,,

In [20]:
# Biotech
crunch(156, 52, ['IBB','XBI','BBH','FBT.MI','BTEC.SW','NBTK.DE','GN0M.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,FBT.MI,First Trust NYSE Arca Biotechnology UCITS ETF ...,EUR,156,19.46%,15.53%,1.00
1,BTEC.SW,iShares Nasdaq US Biotechnology UCITS ETF USD ...,USD,156,17.53%,20.73%,0.65
2,NBTK.DE,Invesco NASDAQ Biotech UCITS ETF,EUR,156,17.52%,20.93%,0.65
3,XBI,State Street SPDR S&P Biotech ETF,USD,156,22.20%,32.95%,0.55
4,IBB,iShares Biotechnology ETF,USD,156,14.44%,19.86%,0.53
5,BBH,VanEck Biotech ETF,USD,156,9.43%,15.86%,0.34
6,GN0M.DE,Global X Genomics & Biotechnology UCITS ETF US...,EUR,156,6.84%,32.29%,0.09

In [23]:
# All UCITS
crunch(156, 52, ['VDIV.DE', 'EHF1.DE', 'ISPA.DE', 'EVSD.DE', 'WQDA.AS', 'EXSH.DE', 'VGWD.DE', 'SELD.DE', 'WTEE.DE', 'IWMO.MI',
                 'XDEM.DE', 'IS3Q.DE', 'XWEM.DE', 'QDVA.DE', 'IUMD.L', 'WMSE.DE', 'FTGM.DE', 'IS3S.DE', 'XDEV.DE', 'CBUI.DE',
                 '5MVL.DE', 'QDVI.DE', 'EUNL.DE', 'QTOP.AS', 'PSWD.DE', 'XWEV.DE', 'SMH.MI', 'CHIP.PA', 'SEC0.DE', 'HNSC.MI',
                 'JEDI.DE', 'ARXX.DE', 'ST4R.DE', 'WSPC.DE', 'ORBT.MI', 'LUNA.DE', 'QUTM.DE', 'WQTM.DE', 'QOMP.DE', 'A1P0.DE',
                 'NUUR.AS', 'WNUC.DE', 'NUKL.DE', 'RCTR.MI', 'ASWA.DE', 'WDNR.DE', 'LOGS.DE', '5MVW.DE', 'XDW0.DE', 'WNRG.MI',
                 'WENE.MI', 'STOR.AS', 'ESIE.DE', 'QDVF.DE', '4MMR.DE', 'DFEN.DE', 'ASWC.DE', 'ES6Y.DE', 'IVDF.DE', 'DFCU.DE',
                 'DAPP.MI', 'EXV1.DE', 'ESIF.DE', '4GLD.DE', 'GLDA.DE', 'PPFB.DE', '8PSG.DE', 'XGDU.DE', 'PHAU.L', 'XDWI.DE',
                 'WIND.AS', 'WMIN.DE', 'XDWM.DE', 'AIFS.DE', 'XAIX.DE', 'XMLD.DE', 'XDWT.DE', 'XLKS.MI', 'FTAI.MI', 'FBT.MI',
                 'BTEC.SW', 'NBTK.DE', 'GN0M.DE'])

,symbol,name,currency,weeks,gmean,std,sharpe
0,EVSD.DE,Global X European Superdividend UCITS ETF EUR ...,EUR,55,45.10%,0.96%,42.73
1,NUUR.AS,iShares Nuclear Energy and Uranium Mining UCIT...,USD,56,13.35%,1.67%,5.61
2,WMSE.DE,Amundi MSCI World Momentum Screened Factor UCI...,EUR,97,29.52%,7.51%,3.40
3,IVDF.DE,Invesco Markets II plc - Invesco Defence Innov...,EUR,99,58.30%,17.69%,3.07
4,AIFS.DE,iShares AI Infrastructure UCITS ETF USD (Acc),EUR,94,73.98%,23.51%,2.98
...,...,...,...,...,...,...,...
78,A1P0.DE,Defiance AI & Power Infrastructure ETF USD Acc,EUR,25,,,
79,RCTR.MI,First Trust Bloomberg Nuclear Power UCITS ETF ...,EUR,33,,,
80,ASWA.DE,Infrastructure Capital Nuclear Renaissance UCI...,EUR,26,,,
81,DFCU.DE,iShares U.S. Aerospace & Defence UCITS ETF USD...,USD,13,,,
82,FTAI.MI,First Trust Bloomberg Artificial Intelligence ...,EUR,7,,,